### ISSUE TITLE
AdGroupsByLabels should inherit AdGroup class

### ISSUE THREAD

**Issue by m-vdb** [facebook/facebook-python-ads-sdk#102]
Otherwise this class really serves for nothing...

**Comment by aparakian** [comment]
+1
There is no remote_update associated to that class?? Why?

**Comment by rituparnamukherjee** [comment]
This class was added only to return the 'adgroupsbylabels' endpoint which is triggered when trying to retrieve all adgroups grouped by an ad label. This call can be made only from an adaccount level (get_ad_groups_by_labels), only for reading purpose.
https://developers.facebook.com/docs/marketing-api/reference/ad-label#Reading

**Comment by m-vdb** [comment]
yes, but what use is it when retrieving the adgroup if we cannot do anything with them?? I get that it's only for the endpoint, but we (as developer and users and contributors of your SDK) should be able to:

- get the adgroups by label (because it's a cool feature from 2.4)
- read more info on the adgroups (remote_read())
- update info on the adgroup (remote_update())
- delete the adgroup (remote_delete())

You only need the endpoint for the first read. But you need the regular adgroup endpoint for the other operation. And I really think everyone would benefit from it
