### ISSUE TITLE
AdAccount.get_ad_label don't return a total

### ISSUE THREAD

**Issue by aparakian** [facebook/facebook-python-ads-sdk#103]
This is not especially a problem from the SDK but a problem for the API.
The call to ``https://graph.facebook.com/<API_VERSION>/act_<AD_ACCOUNT_ID>/adlabels`` with ``summary=1`` as a parameter is not return the ``total_count`` allowing us to get the ``total()`` from the EdgeIterator.
There is no reasons to not return the ``_total_count`` of this iterator because the easiest solution to find the number of objects of the account is to do ``get_ad_object(params={'limit': 1}).total()`` and for the adlabel we would have to do ``len(get_ad_labels(params={'limit': 10000}))`` which we really don't want to...

**Comment by rituparnamukherjee** [comment]
@aparakian, yes this is on the API level. Thanks for the suggestion.
