### ISSUE TITLE
excessive "," characters in the Insights.Field class (in the objects.py file)

### ISSUE THREAD

**Issue by nouvak** [facebook/facebook-python-ads-sdk#105]
When migrating to the v2.5 of the SDK, I noticed strange error in my unit tests:
```
KeyError: "('inline_link_clicks',)"
```

As it turned out, the error appears due to the "," characters that are present after a couple of entries of the Insights.Field class (i.e. cost_per_inline_link_click, cost_per_inline_post_engagement, inline_link_clicks, inline_post_engagement). Because of the "," characters, those entries are treated as tuples instead of strings. 

Those "," characters should probably be removed, right? Or am I missing something.

Greetings
  Marko Novak

**Comment by rituparnamukherjee** [comment]
Hi Nouvak,

Thanks for pointing this out.
Will correct this soon.
