### ISSUE TITLE
No way to fire a conversion success from the server?

### ISSUE THREAD

**Issue by conoremclaughlin** [facebook/facebook-python-ads-sdk#107]
TAG: Question

Hi all,

From what I can tell checking the marketing API docs as well as looking at the SDK here, it seems Facebook does not allow firing the conversion server-to-server. Is that correct? We can achieve all the other management from the server for the campaign, but it seems the client conversion must be done via one of the SDKs.

Thanks so much for any help and sorry to be a bother!
Conor

**Comment by rituparnamukherjee** [comment]
You are right, there is no way to fire conversion from server to server.
