### ISSUE TITLE
'status' parameter is not defined

### ISSUE THREAD

**Issue by shirochan** [facebook/facebook-python-ads-sdk#108]
'status' parameter is not defined in the `facebook/objects.py` required when you creating Capmaign or AdSet or Ad .

https://developers.facebook.com/docs/marketing-api/reference/v2.5_rename/v2.5

**Comment by rituparnamukherjee** [comment]
You will need to pass it as a parameter

campaign = Campaign(parent_id='act-<ACCOUNT_ID>)
...
params = { 'status': Campaign.Status.paused}
campaign.remote_create(params=params)
