### ISSUE TITLE
ReportStats Asynchronous Query

### ISSUE THREAD

**Issue by tpaskhalis** [facebook/facebook-python-ads-sdk#11]
There is currently no straightforward way to fetch Ad Report Stats through asynchronous queries. `get_report_stats` in `AdAccount` only allows direct `GET` requests. And most historical data is not accessible through it, returning error 1487535. Will this be implemented in the future?

**Comment by linpingta** [comment]
Same question, I saw AdStats/ReportStats def but no example of how to use them, is that possible to get related info based on these classes, will that be kindly supported in the future? thanks~

**Comment by cscanlin** [comment]
This issue still remains unresolved. Does anyone know a workaround for this that doesn't involve cURL?

**Comment by ebzlo** [comment]
Hey guys, we're working on building this out. Sorry for the delay.

A workaround would be to use the `FacebookAdsApi::call` method and parse the response yourself.

Here's a sample of how to make a call:
```
# Instantiate an API object (you likely already have one so you
# can use FacebookAdsApi.get_default_api()

api = FacebookAdsApi.get_default_api()
response = api.call('GET', 'https://graph.facebook.com/me')
print response.json()
# Output
# {u'first_name': u'Evan', u'last_name': u'Chen', u'verified': True, u'name': u'Evan C...}
```

**Comment by maimonoded** [comment]
Hi, do you know when a solution will be ready in the sdk ?
