### ISSUE TITLE
get_ads and get_ad_sets return empty list for Campaign object

### ISSUE THREAD

**Issue by fivejjs** [facebook/facebook-python-ads-sdk#112]
From Campaign cannot get ad_sets and ad list any more.
which is get_ads() and get_ad_sets() return empty list for Campaign object

**Comment by rituparnamukherjee** [comment]
Hi fivejjs,

Unable to reproduce this. Just tried reading campaign information and it works fine.
>>> campaign = Campaign([REDACTED])
>>> adsets = campaign.get_ad_sets()
>>> adsets
[<AdSet> {
    "id": "[REDACTED]"
}]
>>> ads = campaign.get_ads()
>>> ads
[<Ad> {
    "id": "[REDACTED]"
}]
