### ISSUE TITLE
insights report no longer accepts "clicks" field in version 2.5

### ISSUE THREAD

**Issue by iditgolden** [facebook/facebook-python-ads-sdk#115]
in version 2.4, when making a call to /insights, a "clicks" field is returned with a certain value.
which field will return the same value in version 2.5? clicks field is no longer permitted.

**Comment by rituparnamukherjee** [comment]
"clicks' was deprecated from /insights in 2.5.  You can use inline_link_clicks https://developers.intern.facebook.com/docs/apps/changelog

**Comment by iditgolden** [comment]
@rituparnamukherjee : thank you, but on the same campaign, when making a call to /insights the value of clicks (in v2.4) and inline_link_clicks (in v2.5) is not the same

**Comment by iditgolden** [comment]
@rituparnamukherjee: ?
