### ISSUE TITLE
Batch requesting Insights

### ISSUE THREAD

**Issue by flux627** [facebook/facebook-python-ads-sdk#116]
Unless I am mistaken, there is currently no way to batch request Insights.

**Comment by kennes913** [comment]
Currently, I am trying to find a way, but haven't found one yet.

**Comment by flux627** [comment]
Thanks. I've fallen back to the horrible solution of using daily scheduled reports emailed to an address and programmatically capturing the results, so anything you find out would be valuable to me.

**Comment by kennes913** [comment]
I found a solution to this problem.

**Comment by rituparnamukherjee** [comment]
You can use the Batch Request API. https://developers.facebook.com/docs/graph-api/making-multiple-requests This should work with Insights too.

**Comment by flux627** [comment]
I can do this with curl as per the examples, however it doesn't seem possible within the Python SDK. Would you be able to give an example of this working with the Python SDK?

**Comment by kennes913** [comment]
I would caution you to use the batch insights if you're pulling a lot of data. I tried using batch insights, but I kept reaching my api rate limits. Instead I created report jobs, store the ids in our db and then run them later:


    def batchInsights(ad_account):
    
        db, cursor = connect_db()

        FacebookAdsApi.init(app_id,app_secret,token)   

        jbid = "https://graph.facebook.com/v2.5/act_{}/insights?".format(ad_account)
        build = FacebookAdsApi.get_default_api().call('POST', jbid, params=params)

        query = {some insert query}.format(ad_account, build.json()['report_run_id'])
        cursor.execute(query)
        db.commit()
    
        return 


    def runReport(report_id):
    
        FacebookAdsApi.init(app_id,app_secret,token)
    
        store = []
        baseUrl = "https://graph.facebook.com/v2.5/{}/insights?&limit=500".format(report_id)
        check = 500
    
        while check == 500: 
    
            call = FacebookAdsApi.get_default_api().call('GET', baseUrl)
            response = call.json()
            {store action}
            check = len(response['data'])
    
            try:
                baseUrl = response['paging']['next']
            except KeyError:
                break 
    
            if check != 500:
                break

        return {stored_data}

**Comment by wdoenlen** [comment]
For others who have been confused about this, here's a short example of how to use the Facebook batch API with the Python SDK to get ad insights:

```
# ----------------------------------------------------------------------------
# Helper functions

def generate_batches(iterable, batch_size_limit):
    # This function can be found in examples/batch_utils.py
    batch = []

    for item in iterable:
        if len(batch) == batch_size_limit:
            yield batch
            batch = []
        batch.append(item)

    if len(batch):
        yield batch

def success_callback(response):
    batch_body_responses.append(response.body())

def error_callback(response):
    # Error handling here
    pass

# ----------------------------------------------------------------------------

batches = []
batch_body_responses = []
api = FacebookAdsApi.init(your_app_id, your_app_secret, your_access_token)

for ad_set_list in generate_batches(ad_sets, batch_limit):
    next_batch = api.new_batch()
    requests = [ad_set.get_insights(pending=True) for ad_set in ad_set_list]
                    
    for req in requests:
        next_batch.add_request(req, success_callback, error_callback)
    batches.append(next_batch)

for batch_request in batches:
    batch_request.execute()
    time.sleep(5)

print batch_body_responses



```

**Comment by rahulpanchal0002** [comment]
How do I get campaign insights passing parameters and selective fields in the above shown example?
