### ISSUE TITLE
Creating lookalike audiences

### ISSUE THREAD

**Issue by beorn** [facebook/facebook-python-ads-sdk#119]
Hi,

I'm trying to follow the blog instructions on how to [create a dynamic targeting with adset conversion lookalike audience](https://developers.facebook.com/ads/blog/post/2014/11/06/campaign-conversion-lookalike/) to create lookalike audiences.  Besides there being a typo in step 4 (*), I just can't make it work - I'm doing this:

```python
lookalike = CustomAudience(parent_id=adaccount_id)
lookalike.update({
    CustomAudience.Field.name: "Test LAL",
    CustomAudience.Field.subtype: CustomAudience.Subtype.lookalike,
    CustomAudience.Field.lookalike_spec: {
        'origin_ids': [seed_adset_id, expand_adset_id],
        'conversion_type': 'mobile_app_installs',
        'ratio': 0.05,
        'country': 'ZA',
    },
})
lookalike.remote_create()
```

with confirmed valid `*id`s (other calls using them work), but I keep getting:

```
  Message: Call was not successful
  Method:  POST
  Path:    https://graph.facebook.com/v2.5/act_***/customaudiences
  Params:  {'subtype': 'LOOKALIKE', 'name': 'Test LAL', 'lookalike_spec': '{"conversion_type":"mobile_app_installs","country":"ZA","origin_ids":["***","***"],"ratio":0.05}'}

  Status:  500
  Response:
    {
      "error": {
        "message": "An unknown error has occurred.", 
        "code": 1, 
        "type": "OAuthException", 
        "fbtrace_id": "AeGdeu9AOys"
      }
    }
```

Is this a bug?  Is there any way to troubleshoot this better?

(*) Step 4: `lookalike_spec=` should be `lookalike_spec:`

**Comment by rituparnamukherjee** [comment]
Hi @beorn,

The account_id in the following statement needs to be pre-fixed by 'act_', so basically it should be 'act_<XXXXXX>'.

lookalike = CustomAudience(parent_id=adaccount_id)

**Comment by beorn** [comment]
@rituparnamukherjee `adaccount_id` is already prefixed (hid the last 4 digits):

```python
seed_adset_id = '603246573xxxx'
expand_adset_id = '603292413xxxx'
adaccount_id = 'act_10496879968xxxx'
```

Any other ideas?  Is there any more info associated with that `fbtrace_id`?

**Comment by rituparnamukherjee** [comment]
The Trace Id doesnt seem to show up anything. But the one thing that I notice is that you are using 'mobile_app_installs' as the conversion type. Going by that you want to create a Dynamic targeting with campaign/adset conversion lookalike you should use 'campaign_conversions' as the conversion type in step 4.

**Comment by beorn** [comment]
That finally works!  Thx!!

In the ad manager web UI, Audience Details only mentions the first `seed_adset_id` - I guess that's just a limitation of the web UI?
