### ISSUE TITLE
'stop_time' field

### ISSUE THREAD

**Issue by leigh-sh** [facebook/facebook-python-ads-sdk#120]
Hi,
I'm trying to fetch the following fields:
campaign = Campaign(campaign_id)
campaign_service = campaign.remote_read(fields="id", "name", "effective_status", "created_time", "stop_time", "buying_type", "objective")

'stop_time' fields doesn't return,
could you please explain what is the meaning of that field?

thanks.

**Comment by rituparnamukherjee** [comment]
Hi @leigh-sh,

The 'stop_time' is the time at which the campaign was stopped. If you campaign is still active, this wont be returned.
