### ISSUE TITLE
'start_time' vs 'created_time'

### ISSUE THREAD

**Issue by leigh-sh** [facebook/facebook-python-ads-sdk#121]
Hi,
What is the difference between the reading field 'start_time' and the reading field 'created_time'?
Currently, when I tried to make a remote reading call for my campaign, the 'created_time' field returned the actual date of the campaign creation while the 'start_time' field returned a date in the year 1969.

Thanks

**Comment by rituparnamukherjee** [comment]
Hi leigh-sh,

created_time is when the object was created and start_time is when the object is scheduled to run. This discrepancy is probably because of the status in which u created the campaign. If the status was set as archived during creation it could have caused this.

**Comment by rituparnamukherjee** [comment]
Hi Leigh-sh,

I think what  you are thinking to be the year 1969 is epoch in PST. epoch in PST timezone is 69. The start time is actually null mostly coz of an archived status or inactive campaign.
