### ISSUE TITLE
<PIXEL_ID>.get_stats() return <AdsPixelStat>  object instead of Iterator

### ISSUE THREAD

**Issue by ipretender** [facebook/facebook-python-ads-sdk#127]
Python 3.4.3; Facebook SDK 2.5.1
 pixel = AdsPixel(PIXEL_ID)
 pixel.get_stats(params={
    'aggregation': 'event',
    'start_time': '2015-12-02', 
    'end_time':'now'})

pixel.get_stats() return AdsPixelStat object. But it have to return Iterator like Ads.get_insights()

**Comment by rituparnamukherjee** [comment]
Hi,

get_stats() will also returns an Edge iterator. Both pixel.get_stats() and Ads.get_insights() are defined in the exact same way in the SDK barring the case where async is set to true for getting insights. If that is not the case then even get_insights() internally calls iterate_edge(). 
Check on https://developers.facebook.com/tools/explorer and query for  <PIXEL_ID>/stats to see the return structure, the SDK will return the same.

**Comment by ipretender** [comment]
Ok, then I don't understand this:
pixel = AdsPixel(PIXEL_ID)
a = pixel.get_stats(params={
    'aggregation': 'event',
    'start_time': '1449378000'
})
>>> type(a)
<class 'facebookads.objects.AdsPixelStat'>

I received only one object but I should receive Iterator

**Comment by ipretender** [comment]
Same moment:
\>>> type(campaign.get_insights(params=params, fields = fields))
\<class 'facebookads.objects.EdgeIterator'\>

**Comment by rituparnamukherjee** [comment]
I see, you are correct. This should be an iterator. Will push this change soon.

**Comment by ipretender** [comment]
same for 2.7.10

**Comment by Jaeto** [comment]
Is there an ETA on when this push will go live? I recently ran into the same error and ended up having to monkeypatch until the fix is public.
