### ISSUE TITLE
Updating examples to use updated libraries

### ISSUE THREAD

**Issue by scottydelta** [facebook/facebook-python-ads-sdk#128]
Upon using this example( https://github.com/facebook/facebook-python-ads-sdk/blob/master/examples/create_ad.py ), it throws error that AdSet.Field doesnt have any attribute called campaign_group_id and status and upon trying to make changes according to the new updated version, I get error saying "Please reduce the amount of data you're asking for, then retry your request". Can you please update the example according to the updated version of the SDK.

**Comment by rituparnamukherjee** [comment]
Hi @scottydelta

Yes, we are in process of updating and adding more examples for the SDK. This will be released soon.

Thanks
