### ISSUE TITLE
can't remove the multi_share_end_card

### ISSUE THREAD

**Issue by FX-HAO** [facebook/facebook-python-ads-sdk#129]
I have gone through the document:
https://developers.facebook.com/docs/marketing-api/guides/carousel-ads/v2.5#spec with:
![qq 20151215155700](https://cloud.githubusercontent.com/assets/6838487/11805155/7fea3c08-a344-11e5-903f-83b5ccf9d659.png)

But i didn't found the **multi_share_end_card** class attribute.

```python
class LinkData(ValidatesFields, AbstractObject):
    class Field(object):
        call_to_action = 'call_to_action'
        caption = 'caption'
        child_attachments = 'child_attachments'
        description = 'description'
        image_hash = 'image_hash'
        image_crops = 'image_crops'
        link = 'link'
        message = 'message'
        multi_share_optimized = 'multi_share_optimized'
        name = 'name'
        picture = 'picture'
```

Is this a bug?And how can i remove the **multi_share_end_card**?

**Comment by rituparnamukherjee** [comment]
Hi,

The Field object only consists of fields which can be read using this endpoint. Will add the 'multi_share_end_card' field after confirming if this is readable. Meanwhile you can set this value using the following syntax while creating link data-
link_data['multi_share_end_card'] = False

**Comment by FX-HAO** [comment]
I tried,and i got the following error:
FacebookBadObjectError: "multi_share_end_card" is not a valid field of LinkData

so this is a bug?

**Comment by rituparnamukherjee** [comment]
Can you try passing it is a param-
params = {
    'message': 'My description',
    'link': '<APP_STORE_URL>',
    'caption': 'WWW.ITUNES.COM',
    'child_attachments': child_attachments,
    'multi_share_optimized': True,
    'multi_share_end_card': False,
   }

data = FacebookAdsApi.get_default_api().\
    call('POST', (<PAGE_ID>, 'feed'), params)

**Comment by FX-HAO** [comment]
It works now :）
