### ISSUE TITLE
I found wrong text in objects.py(class Ad..) in case of pip install 

### ISSUE THREAD

**Issue by rabter** [facebook/facebook-python-ads-sdk#130]
I installed facebookads2.5.1 using pip install.
But I found wrong text in "objects.py". There is "asset_id" that is duplicated in Class Ad in about 1390 line.
Actually, Github version is no problem. I wonder when it will update that problem to latest github version.

**Comment by rituparnamukherjee** [comment]
Hi @rabter,

Will be syncing the pip version with some latest updates very soon.
