### ISSUE TITLE
BRAND_AWARENESS enum is missing from Campaign Objectives

### ISSUE THREAD

**Issue by pita2k** [facebook/facebook-python-ads-sdk#134]
Python latest SDK
BRAND_AWARENESS enum is missing from Campaign Objectives

**Comment by pita2k** [comment]
and spend_cap missing from campaing fields

**Comment by pita2k** [comment]
and LookAlikeAudience.Field.starting_ratio
is missing

**Comment by pita2k** [comment]
BRAND_AWARENESS is also missing from optimization_goals enum

**Comment by rituparnamukherjee** [comment]
Hi @pita2k ,

Thanks for pointing this out. We will be fixing these very soon.

**Comment by pita2k** [comment]
Hi @rituparnamukherjee , Thanks ! :)

**Comment by rituparnamukherjee** [comment]
This is now synced.
