### ISSUE TITLE
Duplicate adset given an adset id, but for another campaign

### ISSUE THREAD

**Issue by dalietimes** [facebook/facebook-python-ads-sdk#135]
I'm wondering if there is a quick way of duplicating an adset along with all of its ads and creatives if I know the adset id. The purpose of this is to create the same adset, but with different targeting options. Right now, I'm creating a new adset, creating a bunch of ads using the creative ids, but it's eating up my API rate limits. I couldn't find an easy way of doing this through this package. Thanks!

**Comment by rituparnamukherjee** [comment]
Duplicating adsets and its components will essentially call the API for each of the creation so not really a way out.
