### ISSUE TITLE
Import AdCampaign, AdGroup fails

### ISSUE THREAD

**Issue by dud3** [facebook/facebook-python-ads-sdk#139]
```py
from facebookads import FacebookSession
from facebookads import FacebookAdsApi
from facebookads.objects import (
    AdUser,
    AdCampaign,
    AdSet,
    AdImage,
    AdCreative,
    AdGroup,
    TargetingSpecsField,
)
````

```sh
    from facebookads.objects import (
ImportError: cannot import name AdCampaign
```

```sh
    from facebookads.objects import (
ImportError: cannot import name AdGroup
```

**Comment by dud3** [comment]
Though I'm unsure if it's the same `sdk` but looking at the main docs: https://developers.facebook.com/docs/marketing-api/reference/ad-campaign-group I see the following: `from facebookads.objects import Campaign`, which it actually works.

**Comment by dud3** [comment]
And would `AdGroup = AdAccountGroup` ?

**Comment by rituparnamukherjee** [comment]
Hi @dud3,

The references to the AdCampaign, AdGroup etc are prevalant in some older example files. We are in process of updating the examples and will update these together shortly. But incase you wish to use these:

AdCampaign == Campaign
AdGroup == Ad

Hope this helps.
