### ISSUE TITLE
Creating Large Custom Audiences gives Facebook Error

### ISSUE THREAD

**Issue by asn264** [facebook/facebook-python-ads-sdk#141]
When using the CreateCustomAudience and LoadCustomAudience functions provided in the examples directory, I receive the following message when trying to upload large (~200,000) audiences. I do not have this issue for smaller audiences (~50). 

u'<!DOCTYPE html>\n<html lang="en" id="facebook">\n  <head>\n    <title>Facebook | Error</title>\n    <meta charset="utf-8">\n    <meta http-equiv="cache-control" content="no-cache">\n    <meta http-equiv="cache-control" content="no-store">\n    <meta http-equiv="cache-control" content="max-age=0">\n    <meta http-equiv="expires" content="-1">\n    <meta http-equiv="pragma" content="no-cache">\n    <meta name="robots" content="noindex,nofollow">\n    <style>\n      html, body {\n        color: #141823;\n        background-color: #e9eaed;\n        font-family: Helvetica, Lucida Grande, Arial,\n                     Tahoma, Verdana, sans-serif;\n        margin: 0;\n        padding: 0;\n        text-align: center;\n      }\n\n      #header {\n        height: 30px;\n        padding-bottom: 10px;\n        padding-top: 10px;\n        text-align: center;\n      }\n\n      #icon {\n        width: 30px;\n      }\n\n      h1 {\n        font-size: 18px;\n      }\n\n      p {\n        font-size: 13px;\n      }\n\n      #footer {\n        border-top: 1px solid #ddd;\n        color: #9197a3;\n        font-size: 12px;\n        padding: 5px 8px 6px 0;\n      }\n    </style>\n  </head>\n  <body>\n    <div id="header">\n      <a href="//www.facebook.com/">\n        <img id="icon" src="//static.xx.fbcdn.net/images/logos/facebook_2x.png" />\n      </a>\n    </div>\n    <div id="core">\n      <h1 id="sorry">Sorry, something went wrong.</h1>\n      <p id="promise">\n        We\'re working on it and we\'ll get it fixed as soon as we can.\n      </p>\n      <p id="back-link">\n        <a id="back" href="//www.facebook.com/">Go Back</a>\n      </p>\n      <div id="footer">\n        Facebook\n        <span id="copyright">\n          &copy; 2016\n        </span>\n        <span id="help-link">\n          &#183;\n          <a id="help" href="//www.facebook.com/help/">Help Center</a>\n        </span>\n      </div>\n    </div>\n    <script>\n      document.getElementById(\'back\').onclick = function() {\n        if (history.length > 1) {\n          history.back();\n          return false;\n        }\n      };\n\n      // Adjust the display based on the window size\n      if (window.innerHeight < 80 || window.innerWidth < 80) {\n        // Blank if window is too small\n        document.body.style.display = \'none\';\n      };\n      if (window.innerWidth < 200 || window.innerHeight < 150) {\n        document.getElementById(\'back-link\').style.display = \'none\';\n        document.getElementById(\'help-link\').style.display = \'none\';\n      };\n      if (window.innerWidth < 200) {\n        document.getElementById(\'sorry\').style.fontSize = \'16px\';\n      };\n      if (window.innerWidth < 150) {\n        document.getElementById(\'promise\').style.display = \'none\';\n      };\n      if (window.innerHeight < 150) {\n        document.getElementById(\'sorry\').style.margin = \'4px 0 0 0\';\n        document.getElementById(\'sorry\').style.fontSize = \'14px\';\n        document.getElementById(\'promise\').style.display = \'none\';\n      };\n    </script>\n  </body>\n</html>\n'

**Comment by rituparnamukherjee** [comment]
@asn264 

This is quite unreadable. But I don't think the size of the audience you are trying to upload should make a difference with respect to the API, unless you are batching this list and making the API call multiple times. Can you share the piece of code using which you are doing this?

**Comment by asn264** [comment]
@rituparnamukherjee 

Hi, I copy-pasted the exact message that was printed to my terminal. It was in HTML so I think that github's website may have interpreted it before posting my message. 

I am using the CreateAudience function provided here: https://github.com/facebook/facebook-python-ads-sdk/blob/master/examples/custom_audience_utils.py

and I modified the LoadCustomAudience function in line 108 because it appears to be looping through string characters rather than lines in a file as intended. So far I have been able to successfully upload even larger audiences (~10,000) but still have the same issue for audiences of size ~300,000

**Comment by rituparnamukherjee** [comment]
@asn264 

I don't think this is an SDK issue, since the call to actually add the users to the custom audience is taking place only once after creating the data array. This might be a transient issue with the API. You can try making batch requests to create the custom audience. As in add the users in a batch of 10K or so if that works, but you might hit API rate limiting in that scenario. 

Try this out and if the API error then you can raise an API bug.

**Comment by asn264** [comment]
@rituparnamukherjee Thanks!
