### ISSUE TITLE
campaign level insights breakdown

### ISSUE THREAD

**Issue by sibiyes** [facebook/facebook-python-ads-sdk#143]
Hi,

I have been using the API to pull insight values broken down by device.

### code snippet #############

params = {
                'date_preset': 'yesterday',
                'breakdowns': ['impression_device', 'placement']          
            }

campaign = Campaign(campaign_id)
insights = campaign.get_insights(params = params)

############################

Suddenly from last night the response doesn't include the breakdown values (impression_device, placement)

The response does include the breakdown values at the account level. The problem is at the campaign level. 

I think this is not an issue with the python API source code as I have been using the script for a while to pull these values. It could be some backend issue. I just wanted to bring this to the attention of someone who can look possibly look into it.

Thanks

Sibi

**Comment by rituparnamukherjee** [comment]
@sibiyes,

Yep, not an SDK issue but thanks for flagging it. Are you still facing this with the API?

**Comment by sibiyes** [comment]
@rituparnamukherjee ,

Hi. The problem appears to be fixed. Thanks for the attention

**Comment by akhiln66** [comment]
@sibiyes ,

Hi, I'm facing the same issue. Following is the error I receive.

Status:  400
  Response:
    {
      "error": {
        "message": "(#100) placement is not valid for breakdowns param. please check https://developers.facebook.com/docs/marketing-api/insights/breakdowns/ for all valid values",
        "type": "OAuthException",
        "code": 100,
        "fbtrace_id": "Hms5C9eWaoF"
      }
    }

Could you please help me with this?

Thank you,
Akhil Nair

**Comment by s73v3p** [comment]
@sibiyes This link might be helpful for you. https://developers.facebook.com/docs/marketing-api/insights/breakdowns/#combiningbreakdowns

**Comment by s73v3p** [comment]
@sibiyes Also you can get the placement by adding 2 breakdowns(publisher_platform,platform_position) in your request.
Eg. 'breakdowns': ['impression_device', 'publisher_platform', 'platform_position']

**Comment by edpruuv** [comment]
Hi @sibiyes did you get the placement value after this?

What does your response object look like?

Your reply is much appreaciated!
