### ISSUE TITLE
"Service Unavailable" response not raised properly

### ISSUE THREAD

**Issue by m-vdb** [facebook/facebook-python-ads-sdk#145]
Hi there,

I found out a breach in the code / API. It looks like the Ads Insights API (and possibly other endpoints) can return a `Service Unavailable` in the response body with a `200` status code.

#### Symptoms
First of all, here is what happened in our code:
```python
# fb_campaign is properly initialized with an id, the api too
stats = fb_campaign.get_insights(fields=['actions'], params={
    'time_range': {
        'since': '2016-01-22', 
        'until': '2016-01-29'
    }
})
```
and the backtrace:
```
TypeError: string indices must be integers
  File "xxxxxx", line 147, in xxxxx
    stats = fb_campaign.get_insights(fields=['actions'], params=params)
  File "facebookads/objects.py", line 1283, in get_insights
    include_summary=False
  File "facebookads/objects.py", line 795, in iterate_edge_async
    include_summary=include_summary
  File "facebookads/objects.py", line 766, in iterate_edge
    iterator.load_next_page()
  File "facebookads/objects.py", line 163, in load_next_page
    self._queue = self.build_objects_from_response(response)
  File "facebookads/objects.py", line 181, in build_objects_from_response
    obj._set_data(data)
  File "facebookads/objects.py", line 444, in _set_data
    self._data[key] = data[key]
```
#### How to fix

[Here](https://github.com/facebook/facebook-python-ads-sdk/blob/2.5.1/facebookads/api.py#L96-L98) there should be a check on the response body, to verify that it's a string and doesn't contains "Service Unavailable". It's a bit dirty and I think you should report this issue internally on your API team. Also, we have this issue several times a week (not too often though), I think it could refer to one of your maintenances.

LMK if you want me to provide a PR to fix it quickly.

**Comment by rituparnamukherjee** [comment]
Hi @m-vdb,

You are right and we have already been talking to our API teams regarding these transient issues and why they are not being reported in a desired way.

Thanks for flagging this.

**Comment by m-vdb** [comment]
thanks @rituparnamukherjee for the quick answer. Do you have any ETA for the fix to be released?

**Comment by rituparnamukherjee** [comment]
Honestly speaking not really. But I can ping back if I get any updates.

**Comment by rituparnamukherjee** [comment]
Though on this note, what I would suggest is that a cleaner way of handling this at your end might be to execute some custom exceptions which internally can basically do a string match to see for these strings. It is okay to not add to the SDK I suppose, coz every developer might want to handle this differently.

**Comment by m-vdb** [comment]
hum I don't want to add crappy code to my codebase so I'll just wait for it to be resolved. I really think that the SDK should handle it though given you're supposed to be the closer possible to the API, and if there's a known issue on the API side, you don't want to impact your SDK users (me :)); that's what FIXMEs are for. But that's just a thought

**Comment by m-vdb** [comment]
I really think this should be reopened @rituparnamukherjee. It can be fixed in a one liner in the codebase of the SDK. If I / other devs have to fix this in their codebase, it involves several lines of crappy code...
