### ISSUE TITLE
Ad.Field.campaign_id is missing from 2.5.1

### ISSUE THREAD

**Issue by caro5** [facebook/facebook-python-ads-sdk#146]
Hi! I noticed that Ad.Field.campaign_id is missing from 2.5.1 but was added in https://github.com/facebook/facebook-python-ads-sdk/commit/57943598fdac5577e825cdc8ad39ecaeb312498d.

Around when will a new tagged release come out with the fixed field?

Thanks!

**Comment by rituparnamukherjee** [comment]
@caro5,

We are looking to add some more new features on the SDK and we will tag a new release with those in a few weeks. For now please clone the version from github. 

Thanks,
Ritu
