### ISSUE TITLE
(#2635) You are calling a deprecated version of the Ads API. Please update to the latest version.

### ISSUE THREAD

**Issue by JorgeBTM** [facebook/facebook-python-ads-sdk#148]
Hi, 

I am trying to use this sdk but I keep getting that error.  Could you please let me know how can this be sorted ?

**Comment by rituparnamukherjee** [comment]
Can you give the details of the call that you are trying to make.

**Comment by rituparnamukherjee** [comment]
The api_version is pulled from the SDK version which is specified in setup.py. Make sure that you have the 2.5.1 version of the SDK and you should not have an issue making the api calls.
