### ISSUE TITLE
Image remote_delete failed

### ISSUE THREAD

**Issue by lucemia** [facebook/facebook-python-ads-sdk#151]
AdImage

```python
E           FacebookRequestError:
E
E             Message: Call was not successful
E             Method:  DELETE
E             Path:    https://graph.facebook.com/v2.5/act_xxxxx/adimages
E             Params:  {}
E
E             Status:  400
E             Response:
E               {
E                 "error": {
E                   "message": "(#100) The parameter hash is required",
E                   "code": 100,
E                   "type": "OAuthException",
E                   "fbtrace_id": "HxW6fzdndgl"
E                 }
E               }
```

**Comment by rituparnamukherjee** [comment]
Yes you do require to pass in the image hash for DELETE request. This is an API requirement-

from facebookads.objects import AdImage

image = AdImage(image_id, ad_account_id)
image.remote_delete(params={AdImage.Field.hash: image_hash})

**Comment by AkashkumarDev** [comment]
how i can get image_id ?

here is code, for uploading image to facebook

    image = AdImage(parent_id=('act_%s' % ad_account_id))
    image[AdImage.Field.filename] = os.path.join(app.config['UPLOAD_FOLDER'], filename)
    image.remote_create()


i can get image_hash through

    image[AdImage.Field.hash]

but not image id
