### ISSUE TITLE
exit() on Slideshow creation

### ISSUE THREAD

**Issue by renzogiust** [facebook/facebook-python-ads-sdk#154]
Hello,
i'm using FB ADS API in order to create slideshows, but the exit() function at row 1927 in object.py stops the execution. What is the particular reason of that function?

`        if self.Field.slideshow_spec in self:
            request = VideoUploadRequest(self.get_api_assured())
            spec = self[self.Field.slideshow_spec]
            print(spec)
            request.setParams(params={'slideshow_spec': {
                'images_urls': self[self.Field.slideshow_spec]['images_urls'],
                'duration_ms': self[self.Field.slideshow_spec]['duration_ms'],
                'transition_ms': self[self.Field.slideshow_spec]['transition_ms'],
            }})
            request.send((self.get_parent_id_assured(), 'advideos'))
           ** exit()
**        elif not (self.Field.filepath in self):
            raise FacebookBadObjectError(
                "AdVideo requires a filepath or slideshow_spec to be defined.",
            )
`

Thanks.

**Comment by rituparnamukherjee** [comment]
closed by last commit
