### ISSUE TITLE
Request fails with "Invalid appsecret_proof" using SDK, succeeds in graph explorer

### ISSUE THREAD

**Issue by d4goxn** [facebook/facebook-python-ads-sdk#155]
If I run this from a Python REPL, I get an `"Invalid appsecret_proof provided in the API argument"`. However, if I use the graph explorer to make a request to `GET https://graph.facebook.com/v2.5/me/adaccounts`, using the same access token, I get a list of my two ad accounts.

Is this an issue for anyone else? Does anyone know of anything that could cause an "invalid appsecret_proof" error, other than an incorrect app ID or app secret? I have triple checked the app ID and app secret, those are definitely correct.

```python
FacebookAdsApi.init("<app id>", "<app secret>", "<user access token, from a user who has ads_management and ads_read permission>")
me = AdUser(fbid="me")
me.get_ad_accounts()
```

```
FacebookRequestError: 

  Message: Call was not successful
  Method:  GET
  Path:    https://graph.facebook.com/v2.5/me/adaccounts
  Params:  {'summary': 'true'}

  Status:  400
  Response:
    {
      "error": {
        "message": "Invalid appsecret_proof provided in the API argument", 
        "code": 100, 
        "type": "GraphMethodException", 
        "fbtrace_id": "<redacted, just in case>"
      }
    }
```

I am using `facebookads==2.5.1`, according to `pip freeze`.

**Comment by d4goxn** [comment]
My bad, I missed a step in the [marketing API quickstart] (https://developers.facebook.com/docs/marketing-api/quickstart#access-token): before generating a user access token, select an app to associate it with. User access tokens are specific to a single user in a single app.

I'm not sure why I was able to use a token that was not associated with an app in the graph explorer, maybe that token is associated with some default graph-explorer app.

**Comment by pembo13** [comment]
Yah, I ran into this misstep as well. There are a lot of tokens that are required, it would be nice if the docs were clearer about this.

**Comment by DenissePerez** [comment]
@d4goxn , @pembo13 Hi, I'm having a lot of troubles with this same issue and don't have much time.  Can you give me a guide on how to deal with this please? I have my developer account, and when trying to create a token I can get personal token or one associated to one of the pages I'm working with, but on my apps, I have only acess to the apps i've created, don't know if I have to ask for access to their apps or something.

Thank you in advance

**Comment by pembo13** [comment]
@DenissePerez sorry, this was well over 18 months ago for me... I can't remember the details. I'm not even sure I have the code for this anymore.
