### ISSUE TITLE
DELETE requests to /{custom_audience}/users fails when using batch calls

### ISSUE THREAD

**Issue by kennes913** [facebook/facebook-python-ads-sdk#156]
Here's a simplified version of code:

    api_batch = API.new_batch()

    for group in audience:
    
        params = {
            "payload":{
                "data":group,
                "schema":'EMAIL_SHA256',
            },  
            "session": {
                "session_id":session_id,
                "batch_seq": batchseq,
                "last_batch_flag": False,
            },
        }
    
        api_batch.add(
          action,
          (audience_id,'users',),
          params=params,
          headers=None, 
          files=None, 
          failure=callback
        )
    
    api_batch.execute()

Error:

    Message: Call was not successful
    Method:  DELETE
    Path:    /
    Params:  None
    
    
    Status:  400
    Response:
    {
      "error": {
        "message": "(#100) Missing required parameter: payload", 
        "code": 100, 
        "type": "OAuthException", 
        "fbtrace_id": "XXXXXXXXX"
      }
    }

Sample call body (you can see **payload** exists):

    {
    'body': 
    'session=%7B%22batch_seq%22%3A1%2C%22last_batch_flag%22%3Afalse%2C%22session_id%22%3A970926%7D&payload=%7B%22data%22%3A%XXXXXXXXXXXX%22%2C%22sc hema%22%3A%22EMAIL_SHA256%22%7D', 
    'method': 'DELETE', 
    'relative_url': u'XXXXXXXXXXXX/users'
    }

One thing I have noticed is that when I use the **.remove_users()** method, the headers for the requests are not the same as below.

Headers from sample call from batch DELETE:

	{u'name': u'Cache-Control', u'value': u'no-store'}, {u'name': u'Vary', u'value': u'Accept-Encoding'}, 
	{u'name': u'Pragma', u'value': u'no-cache'},
	{u'name': u'Content-Type', u'value': u'text/javascript; charset=UTF-8'},
	{u'name': u'Facebook-API-Version', u'value': u'v2.5'},
	{u'name': u'WWW-Authenticate', u'value': u'OAuth "Facebook Platform" "invalid_request" "(#100) Missing required parameter: payload"'},
	{u'name': u'Expires', u'value': u'Sat, 01 Jan 2000 00:00:00 GMT'},
	{u'name': u'Access-Control-Allow-Origin', u'value': u'*'}

**Comment by rituparnamukherjee** [comment]
@lucascosta, we recently puhsed a fix for this. Should be fixed now. We couldn't get to the PR since we were doing some major updates.

**Comment by coisnepe** [comment]
@rituparnamukherjee I'd be interested to know how it was fixed. I'm using the [Koala](https://github.com/arsduo/koala) ruby gem and I keep getting the same error, despite the fact that the hash I'm trying to send does have a `payload` parameter.
