### ISSUE TITLE
Marketing API: ad.get_keyword_stats() gives ASCII error if 'Interest' has non-ASCII characters

### ISSUE THREAD

**Issue by balaca** [facebook/facebook-python-ads-sdk#161]
`C:\Users\xyz\Anaconda\lib\_abcoll.pyc in update(*args, **kwds)
    564             if isinstance(other, Mapping):
    565                 for key in other:
--> 566                     self[key] = other[key]
    567             elif hasattr(other, "keys"):
    568                 for key in other.keys():

C:\Users\xyz\Anaconda\lib\site-packages\facebookads\objects.pyc in __setitem__(self, key, value)
    204 
    205     def __setitem__(self, key, value):
--> 206         self._data[str(key)] = value
    207 
    208     def __delitem__(self, key):

UnicodeEncodeError: 'ascii' codec can't encode character u'\u0101' in position 4: ordinal not in range(128)`

**Comment by rituparnamukherjee** [comment]
Are you still seeing this issue? This should be fixed.

**Comment by rituparnamukherjee** [comment]
If yes, then please reopen the issue.

**Comment by josele86** [comment]
The problem still for me:

oAd.get_keyword_stats()

Returns:

('ascii', u'phone house espa\xf1a', 16, 17, 'ordinal not in range(128)')

My version of pip package is:

facebookads==2.11.3

Please, have any way to solve it?

Thanks a lot

**Comment by albertabello** [comment]
Same issue here, do we have any update?
