### ISSUE TITLE
Edge iteration doesn't pass api to fetched objects

### ISSUE THREAD

**Issue by jcomo** [facebook/facebook-python-ads-sdk#165]
When using edge iteration, it seems appropriate to have the api that is used by the source object be inherited by the target objects. Take this contrived example

```python
# Assume `api' is a FacebookAdsApi
account = AdAccount('act_xxx', api=api)
campaigns = account.get_campaigns()
for campaign in campaigns:
    # This blows up if the default API isn't specified but it seems like it should
    # just use the API client that was used in the original fetch
    ad_sets = campaign.get_ad_sets()
```

If I'm wrong about the intended use case, let me know. Thanks!

**Comment by rituparnamukherjee** [comment]
Please submit a pull request for this feature. We will review it and merge if all goes well.
