### ISSUE TITLE
I found an issue on 'objects.ad' class, there are two 'adset_id' fields, but without 'campaign_id' field.

### ISSUE THREAD

**Issue by yanbf** [facebook/facebook-python-ads-sdk#167]
class Ad(HasStatus, CanArchive, HasAdLabels, AbstractCrudObject):

    class Field(HasBidInfo, object):
        account_id = 'account_id'
        ad_review_feedback = 'ad_review_feedback'
        adlabels = 'adlabels'
        **adset_id = 'adset_id'    # here**
        bid_amount = 'bid_amount'
        bid_info = 'bid_info'
        **adset_id = 'adset_id'    # here**
        configured_status = 'configured_status'
        conversion_specs = 'conversion_specs'
        created_time = 'created_time'
        creative = 'creative'
        effective_status = 'effective_status'

**Comment by rituparnamukherjee** [comment]
This was already addressed in master.
