### ISSUE TITLE
Can you import all objects in facebookads.adbobjects.__init__ file?

### ISSUE THREAD

**Issue by m-vdb** [facebook/facebook-python-ads-sdk#178]
Auto-generated or manually?

cc @rituparnamukherjee

**Comment by rituparnamukherjee** [comment]
Yes you can import all the files in adobjects.

**Comment by m-vdb** [comment]
I think you didn't understand what I meant. I meant writing the following in \_\_init\_\_:
```python
from .adcreative import AdCreative
from .adset import AdSet
# and so on...
```
that way, _us_, users of this SDK, don't have to struggle with 3 levels of imports

**Comment by rituparnamukherjee** [comment]
Ah I see. Doable in my opinion, but will be able to get to it not before later next week.

**Comment by m-vdb** [comment]
ah no rush at all :) it's just an improvement for the SDK use. And also, since you auto generate all the classes, you might be able to auto generate the file too

**Comment by m-vdb** [comment]
(can you re-open the issue then?)

**Comment by rituparnamukherjee** [comment]
done!

**Comment by rituparnamukherjee** [comment]
@m-vdb 

This is causing numerous circular dependency issues in the autogenerated code so will let this be as it is.
Also, looking at the number of classes, now importing all will be waste of memory since not all will be used. 

I am closing this for now.

**Comment by m-vdb** [comment]
have you tried relative imports between the files? because I think that would work
```python
from .adset import AdSet
```
There is no such thing as a waste of memory... Importing your models in the `__init__.py` will warrant every developer can do `from facebookads.adobjects import AdSet, Ad` instead of having 2 lines (and possibly N lines) to import the objects they need. I'm pretty sure you won't have any cyclic import issue when using relative imports :)

**Comment by rituparnamukherjee** [comment]
Yes, we were trying relative imports. There were cyclical dependencies in multiple code generation modules at our end due to this.

**Comment by m-vdb** [comment]
are you saying that the generation didn't work or that the resulting generated code failed due to the `__init__.py` file?

**Comment by rituparnamukherjee** [comment]
Adding the imports were causing cyclical dependencies in code which we are using for autogeneration of these classes. So currently not incuding these change. Can still be done, but will require more work so will keep this in wishlist.

**Comment by rituparnamukherjee** [comment]
cc @JiamingFB

**Comment by m-vdb** [comment]
ok, could the `__init__.py` be included "manually" instead, temporarily?
