### ISSUE TITLE
get all adinsights fields failed with some missing keys

### ISSUE THREAD

**Issue by fivejjs** [facebook/facebook-python-ads-sdk#181]
I want to get adinsights all fields to build report. But the fields in the api docs is different to the fields I can get from code. For instance, I cannot get 'age', 'gender', 'country', 'region' fields.

**Comment by rituparnamukherjee** [comment]
These fields are available under breakdown. Checkout the 'class Breakdowns'. https://github.com/facebook/facebook-python-ads-sdk/blob/master/facebookads/adobjects/adsinsights.py

This was a breaking change for V2.6.
