### ISSUE TITLE
Dynamic Product ads: The schedule of product feeds is not wroking

### ISSUE THREAD

**Issue by FX-HAO** [facebook/facebook-python-ads-sdk#182]
I have gone through the pertinent documents:
[Setup Product Feed][1], [Product Feed Schedule][2].

    product_feed = ProductFeed(parent_id=<PRODUCT_CATALOG_ID>)

    product_feed[ProductFeed.Field.name] = 'Test Feed'
    product_feed[ProductFeed.Field.schedule] = {
        'interval': 'DAILY',
        'url': 'http://ads.example.com/sample_feed.tsv',
        'hour': 22,
    }

    product_feed.remote_create()

A product feed was created, but it never fetch the `sample_feed.csv` from specified url.

Does it not supports HTTP protocol?

  [1]: https://developers.facebook.com/docs/marketing-api/dynamic-product-ads/product-catalog#catalog-update-options
  [2]: https://developers.facebook.com/docs/marketing-api/reference/product-feed-schedule/v2.6

**Comment by FX-HAO** [comment]
code clean

**Comment by rituparnamukherjee** [comment]
Hi @FX-HAO ,

In the example above, the URL mentioned here is just a sample URL, does not have any data there. 
Can you trying a different URL which actually has a feed.
