### ISSUE TITLE
batch call to objects.Ad.remote_update() complains about unexpected "params" keyword

### ISSUE THREAD

**Issue by rjwalters** [facebook/facebook-python-ads-sdk#183]
I get the following error from my script:
`
Traceback (most recent call last):
  File "path", line 174, in <module>
    ad.remote_update(batch=api_batch, success=callback_success, failure=callback_failure,)
  File "path", line 420, in remote_update
    success=callback_success,
TypeError: add_request() got an unexpected keyword argument 'params'
`

This can be fixed by commenting out line 419 in abstractcrudobject.py:
`
            batch_call = batch.add_request(
                request,
                #params=params,
                success=callback_success,
            )
`

I'm calling like this:
`
for ad_batch in batch_list:
    for ad in ad_batch:
        ad[objects.Ad.Field.status] = objects.Ad.Status.paused
        ad.remote_update(batch=api_batch, success=callback_success, failure=callback_failure,)
`

Any advice?

**Comment by rituparnamukherjee** [comment]
When calling the update pass in params = None for this case, instead of commenting it out.  

objects.Ad.Status.paused ad.remote_update(batch=api_batch, params=None, success=callback_success, failure=callback_failure,)

Generally update/create calls expect parameters so that is why it is not defaulted to None.

**Comment by rjwalters** [comment]
Thanks!

**Comment by rjwalters** [comment]
Actually that doesn't seem to fix my problem...

`
add_request() got an unexpected keyword argument 'params'
`

**Comment by rituparnamukherjee** [comment]
@rjwalters 

Oh sorry, can you try params={} instead

**Comment by rjwalters** [comment]
same problem... TypeError: add_request() got an unexpected keyword argument 'params'

**Comment by rjwalters** [comment]
Perhaps in apy.py line 424?
```
    def add_request(
        self,
        request,
        success=None,
        failure=None,
    ):
```

should this include params=None so that we expect the keyword?

**Comment by rituparnamukherjee** [comment]
Oh I see it now. It is in the add_request call. You are right, the parameter 'params' should not be there. I will send out the fix soon. For now please comment it out and move ahead.

Thanks.

**Comment by rjwalters** [comment]
Thanks!
