### ISSUE TITLE
include_summary=False hardcoded on all get_insights requests

### ISSUE THREAD

**Issue by lucascosta** [facebook/facebook-python-ads-sdk#186]
The flag for loading insights summary (`include_summary`) is hardcoded to `False` in the `get_insights` methods, both synchronously and asynchronously. Also, since `response['summary']` is not parsed on  `ObjectParser.parse_single` there is no way for the SDK to return this useful information.

Is there any other recommended way of fetching the summary for insights through the SDK? Would it be possible to make it available? This issue is also present in previous versions.

Thank you

**Comment by rituparnamukherjee** [comment]
You can find details around usage of summary with respects to Insights here. 
https://developers.facebook.com/docs/marketing-api/reference/ad-account/insights/

You can shoose to set this to true in your local code and compare the results :)
