### ISSUE TITLE
objects.AdUser should be linked to user.User instead of adaccountuser.AdAccountUser

### ISSUE THREAD

**Issue by serg472** [facebook/facebook-python-ads-sdk#187]
New `adobjects.user.User` class should correspond to the old `objects.AdUser`, as it contains all the useful methods for retrieving ad accounts and so on. Currently mapped `adobjects.adaccountuser.AdAccountUser` has nothing in it.

https://github.com/facebook/facebook-python-ads-sdk/blob/master/facebookads/objects.py#L115

**Comment by rituparnamukherjee** [comment]
Hi @serg472 

The objects.AdUser class is closer in structure to AdAccountUser objects than to User object. The adobjects.adaccountuser.AdAccountUser imports adaccountusermixin which contains all the requisite methods corresponding to objects.AdUser
