### ISSUE TITLE
Field 'ads' is missing from "act_id/customaudiences" response

### ISSUE THREAD

**Issue by serg472** [facebook/facebook-python-ads-sdk#191]
```
fb_account = objects.AdAccount('act_12345')

fb_audiences = fb_account.get_custom_audiences(params={
    'fields': [
        'id', 
        'name', 
        'adaccounts',
        'ads',
    ],
    'limit': 100
})

print fb_audiences
```

The `ads` field is not present in the result (while `adaccounts` is there). The graph endpoint returns `ads` fine.

**Comment by serg472** [comment]
Actually the whole audience is missing if it has 'ads' field, it is replaced with "cursors" entry. I guess it is related to #190

**Comment by rituparnamukherjee** [comment]
@serg472 

'ads' is not returned in the response even when querying the API directly.
=== Query
  curl -i -X GET \
   "https://graph.facebook.com/v2.6/act_<REDACTED>/customaudiences?fields=id%2Cname%2Caccount_id%2Cads&access_token=<access token sanitized>"


=== Parameters
- Query Parameters

  {
    "fields": "id,name,account_id,ads"
  }
- POST Parameters

  {}
=== Response
  {
    "data": [
      {
        "id": "6047385385016",
        "name": "Product Audience bf84b6f8-0d8a-11e6-bba4-34363bc3fc6c",
        "account_id": "219066941615718"
      }, 

Will check the cursor issue.

**Comment by serg472** [comment]
Graph api does return `ads` field if this audience is used in ads (not returned if not), I'm attaching a screenshot.
![audience_ads](https://cloud.githubusercontent.com/assets/1200229/15159396/734fbd46-16a9-11e6-86ce-9044137b1080.png)

**Comment by rituparnamukherjee** [comment]
Ah I see. Will track this with #190
