### ISSUE TITLE
Warning while creating lookalike audience: "lookalike_spec might not be compatible"

### ISSUE THREAD

**Issue by serg472** [facebook/facebook-python-ads-sdk#192]
When creating lookalike audience you need to provide `lookalike_spec` which is a dictionary, but it shows a warning:

```
/usr/local/lib/python2.7/dist-packages/facebookads/utils/api_utils.py:30: UserWarning: value of lookalike_spec might not be compatible.  Expect string;  got <type 'dict'>
  warnings.warn(message)
```

The code:
```
fb_audience = objects.CustomAudience(parent_id='act_12345')
fb_audience.update({'subtype': u'LOOKALIKE', 'origin_audience_id': u'12345', 'lookalike_spec': {'country': u'US', 'ratio': 0.06}, 'name': 'Lookalike test1'})
fb_audience.remote_create()
```

(I tried creating `lookalike_spec = objects.lookalikespec.LookalikeSpec()` instead of a dictionary and it results in the same warning)

**Comment by rituparnamukherjee** [comment]
Yes, this is because of how the param is decalred in the graph layer. We are working towards fixing these issues. But since these are just warnings, they will not affect your api calls.
