### ISSUE TITLE
Asynchronous Jobs & Batch Requests

### ISSUE THREAD

**Issue by tejasmanohar** [facebook/facebook-python-ads-sdk#195]
What's the main advantage of asynchronous jobs?
- Is this response time significantly faster when fetching a report that was prepared via a job?
- Do you still need to paginate the result of `GET <AD_REPORT_RUN_ID>/insights`, or is all the data unconditionally returned in a single page?

How do asynchronous jobs compare to batch requests? What are the trade-offs? My application is a read-only sync/ETL job.

Docs
- [Asynchronous Jobs](https://developers.facebook.com/docs/marketing-api/insights/async/v2.6)
- [Batch Requests](https://developers.facebook.com/docs/marketing-api/batch-requests/v2.6)

**Comment by rituparnamukherjee** [comment]
Async jobs are essentially only for retrieving insights. Batch requests are SDK specific feature for you to be able to perform bulk CRUD operations using the API. The resonse structure is similar to otehr api so yes you will have to take care of pagination at your end, the advantage is that Async jobs don't time out. 

The two are not exactly comparable, ad you will likely have to use both for different facets of your application.

**Comment by rituparnamukherjee** [comment]
@tejasmanohar 

For similar questions, please utilize the following group https://www.facebook.com/groups/pmdcommunity/

**Comment by tejasmanohar** [comment]
@rituparnamukherjee  Got it. Makes sense. Just requested to join the group! #196 is more specific to this library rather than the FB marketing API.

**Comment by nelsonsequiera** [comment]
@tejasmanohar @rituparnamukherjee I have similar doubts on this. I want to create lot of ads. But i hit rate limit very soon. So I thought ill do it using async method. But you say async is only for getting insights. I cant benefit form async for creating then????

**Comment by tejasmanohar** [comment]
Been far away from FB Ads for a while, sorry :|
