### ISSUE TITLE
Thread-safe / non-blocking

### ISSUE THREAD

**Issue by tejasmanohar** [facebook/facebook-python-ads-sdk#196]
Does this library fully support threads / non-blocking I/O / parallel processing, or are there some processes that would prohibit this? I'm not too adept with Python, but sending requests in parallel is often crucial in performing sync jobs (e.g. reporting / ETL processes) in a timely fashion.

**Comment by tejasmanohar** [comment]
Thoughts? @rituparnamukherjee

**Comment by tejasmanohar** [comment]
ping @rituparnamukherjee

**Comment by wolendranh** [comment]
Any update on this?
