### ISSUE TITLE
Move all imports to top of file

### ISSUE THREAD

**Issue by tejasmanohar** [facebook/facebook-python-ads-sdk#198]
https://github.com/facebook/facebook-python-ads-sdk/blob/master/facebookads/adobjects/campaign.py

Some imports in this package are scoped within functions. This means that on each function call the import is executed, which seems less than ideal for performance reasons (load once vs load every call). Maybe all should be at the top of the file? It's also unconventional afaict.

**Comment by rituparnamukherjee** [comment]
@tejasmanohar 

Yes, these were done, to avoid cicrular dependencies which were occurring when placing all of them at the top of the file.

cc @JiamingFB

**Comment by tejasmanohar** [comment]
example?
