### ISSUE TITLE
social_impressions - Expected Object, got Number

### ISSUE THREAD

**Issue by tejasmanohar** [facebook/facebook-python-ads-sdk#202]
```
UserWarning: Value of social_impressions is not be compatible. Expect Object; got <class 'int'>
```

Getting this warning when fetching insights by campaign. Guessing this means the API changed types for this value & SDK needs to be updated?

**Comment by rituparnamukherjee** [comment]
Hi @tejasmanohar 

Actually this is not an SDK issue. The graph layer defines the type of social_impressions as an object but  an int is returned and the SDK does a type checking and therefore issues this warning.

We are working on making the appropriate changes on the graph layer. For time being please ignore similar warnings.

**Comment by tejasmanohar** [comment]
Awesome, thanks! I did not know that :\

**Comment by tejasmanohar** [comment]
@rituparnamukherjee Not sure if this helps, but I get far more warnings like this when I specify `async=True` on my insights request than without that.
