### ISSUE TITLE
Disable 'App Secret Proof ...'

### ISSUE THREAD

**Issue by tejasmanohar** [facebook/facebook-python-ads-sdk#204]
>IMPORTANT: For extra security, the SDK requires that you turn on 'App Secret Proof for Server API calls' in your app's Settings->Advanced page.

Is this disable-able? Where is it enforced? Want to let people test w/ graph explorer token temporarily / for development

**Comment by rituparnamukherjee** [comment]
This setting is available on your app dashboard https://developers.facebook.com/apps/<APP_ID>/dashboard/ Go to advance settings and turn on appsecret proof. The appsecret proof will be needed while creating the api object. Though I believe, we did add logic to not enforce this and only have access token provided in the api object creation.
