### ISSUE TITLE
Batch create creative, I meet this problem "We had trouble using the URL you provided. Please try  again later.

### ISSUE THREAD

**Issue by PegasusWang** [facebook/facebook-python-ads-sdk#207]
api: https://graph.facebook.com/v2.5/
python api v2.5.0

Hi, when I batch create creative, I meet this problem "We had trouble using the URL you provided. Please try again later." 
details in http://paste.ubuntu.com/17055781/.
Thanks for help.

**Comment by rituparnamukherjee** [comment]
Hey @PegasusWang,

This looks like there was some issue with the API call itself. Could be something to do with the image itself. Can you please post this in the Marketing Developer Community Group (https://www.facebook.com/groups/pmdcommunity/). If required you can also open a bug.
