### ISSUE TITLE
Deprecated Classes for 2.7

### ISSUE THREAD

**Issue by adamgerst** [facebook/facebook-python-ads-sdk#211]
The readme states that the objects module is going to be removed for 2.7 so I started to refactoring our code to import the new adobjects directly.  I noticed that there are several functions that are marked with a deprecated decorator but when I'm wondering if any of the classes are deprecated.

An example of this is the `Campaign` class in 2.5.  It contains a `BuyingType` class and in 2.6 the class still exists inside of `objects.Campaign` but doesn't exist inside of the `adobjects.campaign.Campaign` class.  I checked the marketing-api endpoint documentation (https://developers.facebook.com/docs/marketing-api/reference/ad-campaign-group) and noticed that the possible values for `buying_type` are _AUCTION_ and _RESERVED_ although the `BuyingType` class has _FIXED_PRICE_ as well (I'm assuming this is for backwards compatibility).  Some other classes are a little odd too.  For example, `objects.AsyncJob` is becoming `adobjects.adreportrun.AdReportRun` but it the `AsyncJob` overrides the `__init__` call.  What happens when I change the code over to use the adobjects directly since the adobjects version are different?  My initial guess is that unless this is a bug, `buying_type` is always going to be deprecated (or only be allowed to be _AUCTION_ since it's the default currently) and therefor the `BuyingType` class isn't needed any longer

Any insight into this would be appreciated.  Thanks.

**Comment by rituparnamukherjee** [comment]
cc @JiamingFB

**Comment by rituparnamukherjee** [comment]
Hi @adamgerst,

Sorry for the late reply on this. You are right about the classes like BuyingType to be deprecated. We left it without changes in objects.Campaign for backwards compatibility, but moving forward, please use the adobjects version only. The classes here are much more feature rich and in parity with the Marketing API docs so hopefully just going by them created less confusion.
