### ISSUE TITLE
FacebookRequestError has no default value for _api_error_subcode

### ISSUE THREAD

**Issue by lwolf** [facebook/facebook-python-ads-sdk#213]
FacebookRequestError does not assign default value during class init to [`self._api_error_subcode`](https://github.com/facebook/facebook-python-ads-sdk/blob/master/facebookads/exceptions.py#L76).
This leads to `AttributeError` when you try to use `api_error_subcode` method.

**Comment by tejasmanohar** [comment]
I think this is reasonable. Subcodes are optional, no?

**Comment by lwolf** [comment]
Subcodes are optional, but public method should not rise exception. Subcode attribute should be set to  `None` by default, just like all other attributes.

For  `self._api_blame_field_specs` is also optional, but it set to None by default.

**Comment by tejasmanohar** [comment]
ah, missed that there's a method being called here

**Comment by rituparnamukherjee** [comment]
@lwolf,

Thanks for bringing this up. We will fix this soon.

**Comment by rituparnamukherjee** [comment]
Fixed by last commit
