### ISSUE TITLE
attribution window for conversion in get_insights for adsets

### ISSUE THREAD

**Issue by sibiyes** [facebook/facebook-python-ads-sdk#215]
Hi,

Facebook recently introduced new pixel (fb_pixel) for tracking conversion. This came up with different attribution models for measuring those conversion. 

When I try to pull the insights for an adset, the offsite conversion metric corresponding to fb_pixel returns a number, but I don't know the attribution model associated with the value returned. Is there any default value for the attribution model ? How do I specify the attribution model that I am interested in ?

Thanks

Sibi

**Comment by rituparnamukherjee** [comment]
Hi @sibiyes,

Can you direct this question in the Marketing API Developers group. This seems like a API specific question not an SDK one. You are likely to get a more accurate response there. 
https://www.facebook.com/groups/pmdcommunity/
