### ISSUE TITLE
 What is the Conversion Events(optimization_goal) in API?

### ISSUE THREAD

**Issue by m18664319351** [facebook/facebook-python-ads-sdk#216]
Hi：
![image](https://cloud.githubusercontent.com/assets/17756466/16258505/daba206c-3890-11e6-8248-9282cf15a25d.png)

Now,I want to create adset by api,but the api only have five valid optimization_goal, I'm not find the Conversion Events in api

api url:https://developers.facebook.com/docs/marketing-api/validation/v2.5#bid_conversion
![image](https://cloud.githubusercontent.com/assets/17756466/16258825/16cb7b7c-3892-11e6-9738-ce7851cffd8c.png)

Thanks.

**Comment by rituparnamukherjee** [comment]
I believe conversion event refers to 'OFFSITE_CONVERSIONS' goal.
