### ISSUE TITLE
2.6.2 version published on pypi is wrong

### ISSUE THREAD

**Issue by m-vdb** [facebook/facebook-python-ads-sdk#224]
Hi there,

The version you published on [pypi](https://pypi.python.org/pypi/facebookads) is not the same as the tag of your github repository. And the reason why I found out that issue is because **`AbstractCrudObject.remote_update()` doesn't work when used in batch mode**. Here is the backtrace:
```
File "/home/vagrant/work4us/venv/local/lib/python2.7/site-packages/facebookads/adobjects/abstractcrudobject.py", line 420, in remote_update
    success=callback_success,\nTypeError: add_request() got an unexpected keyword argument \'params\''
```
This is pretty serious because it touches everyone that uses your SDK. Can you do a new release on pypi as soon as possible? Your deadline to migrate to 2.6 version is supposed to be July 13th (a few days from now). How are we supposed to migrate if half of your code is not working?

Please fix this.

**Comment by aparakian** [comment]
wow that's pretty critical!

**Comment by rituparnamukherjee** [comment]
Hi @m-vdb,

To clarify, the remote_update is not working when downloaded from pypi?

**Comment by m-vdb** [comment]
yes

**Comment by rituparnamukherjee** [comment]
There should be a new release on pypi 2.6.2.0 which should be in sync with latest on github.

**Comment by m-vdb** [comment]
thanks for your reactivity.
