### ISSUE TITLE
Bad typecheck for Ad.tracking_specs

### ISSUE THREAD

**Issue by m-vdb** [facebook/facebook-python-ads-sdk#228]
Hi there,

Found [this inconsistency](https://github.com/facebook/facebook-python-ads-sdk/blob/master/facebookads/adobjects/ad.py#L204) with the [API definition](https://developers.facebook.com/docs/marketing-api/reference/adgroup). It should be `list<Object>` instead of `Object` or even `list<ConversionActionQuery>`. Since this looks like autogenerated code (...) can you fix this quickly and make a release?

Cheers
cc @fbach

**Comment by rituparnamukherjee** [comment]
@m-vdb,

The type associated with updating tracking specs for an ad is Object https://developers.facebook.com/docs/marketing-api/reference/adgroup#Creating 

That is why the autogenerated code has the same. The type associated with the field while reading it is list<ConversionActionQuery>

**Comment by m-vdb** [comment]
wow, and how does the update works? Does it add the element to the list? How can we remove element from the list? Has it changed in 2.6?
