### ISSUE TITLE
AdSet can no longer call remote_validate()

### ISSUE THREAD

**Issue by TheDan64** [facebook/facebook-python-ads-sdk#229]
Hi, I'm attempting to update from v2.5.1 to v2.6.2 and it seems as though a `facebookads.objects.AdSet` object no longer has a `remote_validate()` method?

This is a much needed piece of functionality.

Thanks for your time,
Dan

**Comment by TheDan64** [comment]
Hello again, I've just come across a similar issue so instead of creating another ticket I'll add it here.

`facebookads.objects.Ad` seems to also be missing a `get_click_tracking_tag()` method which was present previously.

**Comment by rituparnamukherjee** [comment]
Validate issue fixed by last commit
