### ISSUE TITLE
examples reference class that does not exist

### ISSUE THREAD

**Issue by captbaritone** [facebook/facebook-python-ads-sdk#231]
From: https://github.com/facebook/facebook-python-ads-sdk/blob/master/examples/create_ad.py#L133

```
### Get excited, we are finally creating an ad!!!
ad = AdGroup(parent_id=my_account.get_id_assured())
ad.update({
    AdGroup.Field.name: 'Puget Sound impression ad',
    AdGroup.Field.campaign_id: ad_set.get_id_assured(),
    AdGroup.Field.creative: {
        AdGroup.Field.Creative.creative_id: creative.get_id_assured(),
    },
})
```

`AdGroup.Field` no longer has an attribute `Creative`.

**Comment by captbaritone** [comment]
The API docs use a literal string: 

![screen shot 2016-07-11 at 5 07 38 pm](https://cloud.githubusercontent.com/assets/162735/16750915/0c9ab2ce-478a-11e6-932b-72165b5f6c27.png)

**Comment by morocarlo** [comment]
Hi, same issue for me. Have you solved?

**Comment by guxufb** [comment]
Please note that adgroup has been renamed to ad.  Similarly, campaign_group -> campaign, campaign -> adset.  Also, we are depreciating ad creation with parent_id.  The right way to do creation is:
  `act = new AdAccount(my_account.get_id_assured())`
   `ad = act.create_ad(...)`

You can also try out our code-generation wizard.  https://developers.facebook.com/apps/<app_id>/marketing-api/quickstart/
