### ISSUE TITLE
Campaign level insights

### ISSUE THREAD

**Issue by ddd-malay** [facebook/facebook-python-ads-sdk#235]
When insights are fetched on an account by setting level=campaign, campaign_id and campaign_name are **not** being returned.

`acc = objects.AdAccount(fbid=<acc_id>)`
`params = {
    'level' : objects.Insights.Level.campaign,
     }`
`insights = acc.get_insights(params=params)`

In insights, 'campaign_id' is not returned.

Output:

`<AdsInsights> {
    "account_id": "xxxxxxxxx",
    "date_start": "2016-07-20",
    "date_stop": "2016-07-20",
    "impressions": "69603",
    "spend": 274.03
}`

Data pertains to one of the campaigns, but there is no campaign_id.

**Comment by rituparnamukherjee** [comment]
I believe this is the default API behavior. What happens when you make the same call directly via graph explorer or curl?

**Comment by guxuoss** [comment]
It is by-design.  If you need campaign_id, you need to specify it in the fields. 
https://developers.facebook.com/docs/marketing-api/insights/fields/v2.7

**Comment by guxuoss** [comment]
close this as it seems to be resolved.
