### ISSUE TITLE
No way to read 'Delivery' status

### ISSUE THREAD

**Issue by wolfgangstar** [facebook/facebook-python-ads-sdk#238]
Is there a way to read the "Delivery" status column associated with campaigns, ad sets, and ads in the Facebook Ads Manager? For example, the column that indicates "Recently Completed", "Not Delivering", etc.

If not, is there an alternative method for detecting whether an ad campaign has completed?

**Comment by JiamingFB** [comment]
Hi wolfgangstar,

You can read the effective_status field for this purpose.

**Comment by wolfgangstar** [comment]
JiamingFB, which of the following Campaign.EffectiveStatus values equates to "Recently Completed"?

```
    class EffectiveStatus:
        active = 'ACTIVE'
        paused = 'PAUSED'
        deleted = 'DELETED'
        pending_review = 'PENDING_REVIEW'
        disapproved = 'DISAPPROVED'
        preapproved = 'PREAPPROVED'
        pending_billing_info = 'PENDING_BILLING_INFO'
        campaign_paused = 'CAMPAIGN_PAUSED'
        archived = 'ARCHIVED'
        adset_paused = 'ADSET_PAUSED'
```
