### ISSUE TITLE
No way to read whether Campaign is "Recently Completed"

### ISSUE THREAD

**Issue by wolfgangstar** [facebook/facebook-python-ads-sdk#246]
There is no apparent way to read whether a campaign is "Recently Completed" through the API. This information is reflected in the Ads Manager in the "Delivery" column.

JiamingFB suggested that this information is available in Campaign.effective_status. If so, please suggest which of the following states equates to "Recently Completed".

```
    class EffectiveStatus:
        active = 'ACTIVE'
        paused = 'PAUSED'
        deleted = 'DELETED'
        pending_review = 'PENDING_REVIEW'
        disapproved = 'DISAPPROVED'
        preapproved = 'PREAPPROVED'
        pending_billing_info = 'PENDING_BILLING_INFO'
        campaign_paused = 'CAMPAIGN_PAUSED'
        archived = 'ARCHIVED'
        adset_paused = 'ADSET_PAUSED'
```

**Comment by cloudxu** [comment]
That status is some internal logic Ad Manager decides to implement. So it is not really part of the Campaign data model, and of course is not in SDK.

**Comment by wolfgangstar** [comment]
cloudxu, thank you for your response.
