### ISSUE TITLE
Catalog & Feed product count

### ISSUE THREAD

**Issue by redbild** [facebook/facebook-python-ads-sdk#248]
Hi,

I'm trying to compare product count between catalog and feed, and I saw there are product count field in catalog and feed also. But when I pull these data, the data I got are the same. Both of data are product count of catalog. So how can I get the product count of feed as shown in column status in product catalogs ?

Thank you,
Nattapon Werayawarangura

**Comment by cloudxu** [comment]
Hi @redbild, I think this is a Dynamic Ads specific question and doesn't seems to be an SDK issue. Could you ask the question in the Facebook group https://www.facebook.com/groups/pmdcommunity/
