### ISSUE TITLE
facebookads/utils/api_utils.py:30: UserWarning: Value of device_platforms is not be compatible. Expect DevicePlatforms; got <type 'list'>

### ISSUE THREAD

**Issue by vicngtor** [facebook/facebook-python-ads-sdk#257]
In the python file it's expecting DevicePlatform.mobile or DevicePlatform.desktop whereas the API is actually expecting a list. 

Is this a bug?

**Comment by ekoly** [comment]
Yes, this issue was reported in https://github.com/facebook/facebook-python-ads-sdk/issues/237

**Comment by daphyFB** [comment]
Thank you for reporting. we'll track with #237 .
