### ISSUE TITLE
has_error flag deprecated to? 

### ISSUE THREAD

**Issue by vicngtor** [facebook/facebook-python-ads-sdk#260]
![71jrv5k2eywe](https://cloud.githubusercontent.com/assets/549987/18704597/25090010-801d-11e6-9eae-3d81b003bfa4.png)

Hi everyone, 

I am trying to access: `lifetime_target_spend` and `today_target_spend` from https://developers.facebook.com/docs/marketing-api/reference/ad-entity-target-spend 

I believe both are deprecated and so is Ad Entity. 

Does the current Marketing API support both of these fields? If so, how can I retrieve them?

**Comment by lintaocui** [comment]
hi @vicngtor Thanks for reporting facebook ads api bugs.

Right now, we don't expose those two fields.

Thanks.
