### ISSUE TITLE
ProductCatalog.delete_external_event_sources has been removed

### ISSUE THREAD

**Issue by adamgerst** [facebook/facebook-python-ads-sdk#262]
I was preparing for the upcoming 2.7 breaking changes and noticed that the 2.7.1 sdk no longer has the `delete_external_event_sources` on the `ProductCatalog` object.  I tested the 2.7 api and we are still able to make an `HTTP DELETE` call so my assumption is that this functionality wasn't supposed to be removed.  Am I correct? Because we currently depend on this method/functionality

**Comment by guxuoss** [comment]
Thanks for the feedback!  I think you can use "remove_external_event_sources" instead.  Also in the latest version, we already add "delete_external_event_sources" back.  We know it might be hard to move to v2.8 now and we are planning to support two active versions in Github.

**Comment by JiamingFB** [comment]
(Assuming issue resolved as no further comments are made)
