### ISSUE TITLE
Adding proxies for requests

### ISSUE THREAD

**Issue by prateeksan** [facebook/facebook-python-ads-sdk#263]
I was wondering if it will be possible to allow adding proxies with requests? The requests library being used supports proxies (http://docs.python-requests.org/en/master/user/advanced/#proxies) and I believe so does the facebook-sdk (http://facebook-sdk.readthedocs.io/en/latest/api.html). I could take a shot at building it if you are accepting pull requests.

**Comment by xiaotchen** [comment]
Thanks for opening the Ads API SDK issue! You are requesting a new feature for Ads API SDK and yes, we're actively accepting pull requests as long as the codegen files aren't modified (codegen files are titled with comments like https://github.com/facebook/facebook-python-ads-sdk/blob/master/facebookads/adobjects/ad.py#L28-L34). Thank you so much for your contribution! I'm closing the issue now but please let me know if you have any questions!
