### ISSUE TITLE
AdActivity Sorting

### ISSUE THREAD

**Issue by ddd-malay** [facebook/facebook-python-ads-sdk#266]
Until recently, data from /adaccount/activities endpoint was sorted in reverse chronological order. However, I recently observed that data is not longer sorted (see sample). For sorting, it will helpful to have an implementation of `__cmp__` on AdActivity class, with number being the timestamp (field '**event_time**').

Sample output from `act_xxxxxxxxxx/activities?fields=date_time_in_timezone`

>   "data": [
>     {
>       "date_time_in_timezone": "10/14/2016 at 7:19pm"
>     },
>     {
>       "date_time_in_timezone": "10/14/2016 at 7:19pm"
>     },
>     {
>       "date_time_in_timezone": "10/14/2016 at 7:18pm"
>     },
>     {
>       "date_time_in_timezone": "10/14/2016 at 7:17pm"
>     },
>     {
>       "date_time_in_timezone": "10/14/2016 at 7:16pm"
>     },
>     {
>       "date_time_in_timezone": "10/14/2016 at 7:16pm"
>     },
>     {
>       "date_time_in_timezone": "10/14/2016 at 7:16pm"
>     },
>     {
>       "date_time_in_timezone": "10/14/2016 at 7:16pm"
>     },
>     {
>       "date_time_in_timezone": "10/14/2016 at 7:16pm"
>     },
>     {
>       "date_time_in_timezone": "10/14/2016 at 7:16pm"
>     },
>     {
>       "date_time_in_timezone": "10/14/2016 at 7:16pm"
>     },
>     {
>       "date_time_in_timezone": "10/14/2016 at 7:16pm"
>     },
>     {
>       "date_time_in_timezone": "10/14/2016 at 7:16pm"
>     },
>     {
>       "date_time_in_timezone": "10/14/2016 at 7:16pm"
>     },
>     {
>       "date_time_in_timezone": "10/14/2016 at 5:51pm"
>     },
>     {
>       "date_time_in_timezone": "10/14/2016 at 5:52pm"
>     },
>     {
>       "date_time_in_timezone": "10/14/2016 at 5:52pm"
>     },
>     {
>       "date_time_in_timezone": "10/14/2016 at 5:53pm"
>     },
>     {
>       "date_time_in_timezone": "10/14/2016 at 5:53pm"
>     },
>     {
>       "date_time_in_timezone": "10/14/2016 at 5:53pm"
>     },
>     {
>       "date_time_in_timezone": "10/14/2016 at 5:53pm"
>     },
>     {
>       "date_time_in_timezone": "10/14/2016 at 5:53pm"
>     },
>     {
>       "date_time_in_timezone": "10/14/2016 at 5:53pm"
>     },
>     {
>       "date_time_in_timezone": "10/14/2016 at 5:54pm"
>     },
>     {
>       "date_time_in_timezone": "10/14/2016 at 5:54pm"
>     },
>     {
>       "date_time_in_timezone": "10/14/2016 at 5:55pm"
>     },
>     {
>       "date_time_in_timezone": "10/14/2016 at 5:55pm"
>     },
>     {
>       "date_time_in_timezone": "10/14/2016 at 5:55pm"
>     },
>     {
>       "date_time_in_timezone": "10/14/2016 at 5:55pm"
>     },
>     {
>       "date_time_in_timezone": "10/14/2016 at 5:55pm"
>     },
>     {
>       "date_time_in_timezone": "10/14/2016 at 5:55pm"
>     },
>     {
>       "date_time_in_timezone": "10/14/2016 at 5:56pm"
>     },
>     {
>       "date_time_in_timezone": "10/14/2016 at 6:03pm"
>     },
>     {
>       "date_time_in_timezone": "10/14/2016 at 6:03pm"
>     },
>     {
>       "date_time_in_timezone": "10/14/2016 at 6:03pm"
>     },
>     {
>       "date_time_in_timezone": "10/14/2016 at 6:08pm"
>     },
>     {
>       "date_time_in_timezone": "10/14/2016 at 6:08pm"
>     },
>     {
>       "date_time_in_timezone": "10/14/2016 at 6:08pm"
>     },
>     {
>       "date_time_in_timezone": "10/14/2016 at 6:08pm"
>     },
>     {
>       "date_time_in_timezone": "10/14/2016 at 6:09pm"
>     },
>     {
>       "date_time_in_timezone": "10/14/2016 at 6:09pm"
>     },
>     {
>       "date_time_in_timezone": "10/14/2016 at 6:09pm"
>     },
>     {
>       "date_time_in_timezone": "10/14/2016 at 6:09pm"
>     },
>     {
>       "date_time_in_timezone": "10/14/2016 at 6:09pm"
>     },
>     {
>       "date_time_in_timezone": "10/14/2016 at 6:09pm"
>     },
>     {
>       "date_time_in_timezone": "10/14/2016 at 6:10pm"
>     },
>     {
>       "date_time_in_timezone": "10/14/2016 at 6:10pm"
>     },
>     {
>       "date_time_in_timezone": "10/14/2016 at 6:10pm"
>     },
>     {
>       "date_time_in_timezone": "10/14/2016 at 6:10pm"
>     },
>     {
>       "date_time_in_timezone": "10/14/2016 at 6:11pm"
>     },
>     {
>       "date_time_in_timezone": "10/14/2016 at 6:11pm"
>     },
>     {
>       "date_time_in_timezone": "10/14/2016 at 6:11pm"
>     },
>     {
>       "date_time_in_timezone": "10/14/2016 at 6:11pm"
>     },
>     {
>       "date_time_in_timezone": "10/14/2016 at 6:11pm"
>     },
>     {
>       "date_time_in_timezone": "10/14/2016 at 6:12pm"
>     },
>     {
>       "date_time_in_timezone": "10/14/2016 at 6:12pm"
>     },
>     {
>       "date_time_in_timezone": "10/14/2016 at 6:12pm"
>     },
>     {
>       "date_time_in_timezone": "10/14/2016 at 6:12pm"
>     },
>     {
>       "date_time_in_timezone": "10/14/2016 at 6:12pm"
>     },
>     {
>       "date_time_in_timezone": "10/14/2016 at 6:12pm"
>     },
>     {
>       "date_time_in_timezone": "10/14/2016 at 6:31pm"
>     },
>     {
>       "date_time_in_timezone": "10/14/2016 at 6:31pm"
>     },
>     {
>       "date_time_in_timezone": "10/14/2016 at 6:31pm"
>     },
>     {
>       "date_time_in_timezone": "10/14/2016 at 6:31pm"
>     },
>     {
>       "date_time_in_timezone": "10/14/2016 at 6:31pm"
>     },
>     {
>       "date_time_in_timezone": "10/14/2016 at 6:31pm"
>     },
>     {
>       "date_time_in_timezone": "10/14/2016 at 6:31pm"
>     },
>     {
>       "date_time_in_timezone": "10/14/2016 at 6:38pm"
>     },
>     {
>       "date_time_in_timezone": "10/14/2016 at 6:38pm"
>     },
>     {
>       "date_time_in_timezone": "10/14/2016 at 6:43pm"
>     },
>     {
>       "date_time_in_timezone": "10/14/2016 at 6:49pm"
>     },
>     {
>       "date_time_in_timezone": "10/14/2016 at 6:49pm"
>     },
>     {
>       "date_time_in_timezone": "10/14/2016 at 6:51pm"
>     },
>     {
>       "date_time_in_timezone": "10/14/2016 at 6:51pm"
>     },
>     {
>       "date_time_in_timezone": "10/14/2016 at 6:51pm"
>     },
>     {
>       "date_time_in_timezone": "10/14/2016 at 6:53pm"
>     },
>     {
>       "date_time_in_timezone": "10/14/2016 at 6:57pm"
>     },
>     {
>       "date_time_in_timezone": "10/14/2016 at 7:04pm"
>     },
>     {
>       "date_time_in_timezone": "10/14/2016 at 7:04pm"
>     },
>     {
>       "date_time_in_timezone": "10/14/2016 at 7:04pm"
>     },
>     {
>       "date_time_in_timezone": "10/14/2016 at 7:04pm"
>     },
>     {
>       "date_time_in_timezone": "10/14/2016 at 7:08pm"
>     },
>     {
>       "date_time_in_timezone": "10/14/2016 at 7:08pm"
>     },
>     {
>       "date_time_in_timezone": "10/14/2016 at 7:10pm"
>     },
>     {
>       "date_time_in_timezone": "10/14/2016 at 7:10pm"
>     },
>     {
>       "date_time_in_timezone": "10/14/2016 at 7:10pm"
>     },
>     {
>       "date_time_in_timezone": "10/14/2016 at 7:11pm"
>     },
>     {
>       "date_time_in_timezone": "10/14/2016 at 7:11pm"
>     },
>     {
>       "date_time_in_timezone": "10/14/2016 at 7:11pm"
>     },
>     {
>       "date_time_in_timezone": "10/14/2016 at 7:12pm"
>     },
>     {
>       "date_time_in_timezone": "10/14/2016 at 7:12pm"
>     },
>     {
>       "date_time_in_timezone": "10/14/2016 at 7:12pm"
>     },
>     {
>       "date_time_in_timezone": "10/14/2016 at 7:12pm"
>     },
>     {
>       "date_time_in_timezone": "10/14/2016 at 7:13pm"
>     },
>     {
>       "date_time_in_timezone": "10/14/2016 at 7:13pm"
>     },
>     {
>       "date_time_in_timezone": "10/14/2016 at 7:13pm"
>     },
>     {
>       "date_time_in_timezone": "10/14/2016 at 7:13pm"
>     },
>     {
>       "date_time_in_timezone": "10/14/2016 at 7:13pm"
>     },
>     {
>       "date_time_in_timezone": "10/14/2016 at 7:13pm"
>     },
>     {
>       "date_time_in_timezone": "10/14/2016 at 3:32pm"
>     }
>   ],

**Comment by JiamingFB** [comment]
Hi @ddd-malay 

You can achieve this by sorting the list with your custom comparison function like `list.sort([func])`.
(Currently API doesn't guarantee the order of events.)

Feel free to reopen if you have additional questions.
