### ISSUE TITLE
How to get deleted performance metrics on deleted campaigns / adsets from Insights API ?

### ISSUE THREAD

**Issue by ssundara-nw** [facebook/facebook-python-ads-sdk#269]
Hi Guys,

Campaign / Adset metrics we get from API are not matching with what we see on FB Ads manager reports. I think we know the reason being UI has a filter - "Had Delivery" and this includes metrics on deleted campaings.

How to get deleted performance metrics on deleted campaigns / adsets from Insights API ?

related threads,
http://stackoverflow.com/questions/33571976/facebook-ads-api-retrieving-deleted-object-ids-from-parent-node

**Comment by HndrkMkt** [comment]
Hi @ssundara-nw,

as stated in the first link of the answer in the stackoverflow post, you can still retrieve the performance metrics of adobjects by directly addressing them using their id, but not by querying an upper level object's descendants:

> If you keep the deleted object id, you can continue to retrieve the stats or object details by individually querying the object ID. However you cannot retrieve the deleted objects as a connection object from a non deleted node/object. e.g. `<API_VERSION>/<AD_ID>/insights` works for a deleted object but `<API_VERSION>/act_<AD_ACCOUNT_ID>/insights?level=ad` will not return stats for the deleted object.

https://developers.facebook.com/docs/marketing-api/best-practices/storing_adobjects#deleted

As a workaround I see three possible scenarios: You could either store the history of the structure and query all missing ads directly, store the history of the performance data directly and upsert this, or calculate the difference between the upper level object's performance and the aggregate of the individual objects (this will only work for certain measures obviously).

**Comment by JiamingFB** [comment]
Thank you @HndrkMkt !

Unfortunately this is a limitation for current Graph API. There is not much we can do on the SDK side :(

You can report an API issue at https://developers.facebook.com/bugs/ . People may start working to improve on it. it will take some time though...

**Comment by tosolveit** [comment]
Hi @HndrkMkt ,
I've been working on the similar problem and couldn't find a solution yet, I need to get spending data for deleted campaigns.

When I use an active campaign id `apiversion/an_active_campaign_id/insights?fields=impressions,campaign_name,spend`  I get the results by api explorer, but when I use a deleted campaign It does not return any data, I checked that there is over 10k spending on facebook business manager. ( business manager shows the status as deleted, when I use effective_status parameter for that deleted campaign, it returns status as ARCHIVED)

Your solution is for adsets but I applied it for campaign and it didn't work, so what's the point that I'm missing. Thanks you so much for your help.

**Comment by fabioknoedtbcgdv** [comment]
Apply a `filtering` for all `delivery_info` states.
Then you get all campaigns / adsets / ads, even they were deleted or archived.
```
'filtering': [{
        "field": "ad.delivery_info",
        "operator": "IN",
        "value": ["active", "archived", "completed", "limited", "not_delivering", "not_published", "pending_review", "permanently_deleted", "recently_completed", "recently_rejected", "rejected", "scheduled", "inactive"]
      }]
```
or 
```
'filtering': [{
        "field": "adset.delivery_info",
        "operator": "IN",
        "value": ["active", "archived", "completed", "limited", "not_delivering", "not_published", "pending_review", "permanently_deleted", "recently_completed", "recently_rejected", "rejected", "scheduled", "inactive"]
      }]
```
or
```
'filtering': [{
        "field": "campaign.delivery_info",
        "operator": "IN",
        "value": ["active", "archived", "completed", "limited", "not_delivering", "not_published", "pending_review", "permanently_deleted", "recently_completed", "recently_rejected", "rejected", "scheduled", "inactive"]
      }]
```

**Comment by madhavimohoni** [comment]
Why was the last answer downvoted? Does it not work?

**Comment by thomiko** [comment]
I don't understand the downvote on the response of @fabioknoedtbcgdv either. This works perfectly for me with the fbRads R package. Thanks for the info!

P.S. I know that this is the Python Ads SDK but this solution is language-agnostic ;-)

**Comment by Knifven** [comment]
Can confirm that @fabioknoedtbcgdv fix works. Just downloaded deleted ads from the insights endpoint using it.

**Comment by matiasbeltramone** [comment]
@fabioknoedtbcgdv u're awesome thanks!

**Comment by Alonreznik** [comment]
Hi.
Where is described the `delivery_info` field in the doc?
I can't find it in the reference of the `ad` entity.

Thanks!

**Comment by rodneyo** [comment]
is ad.directory_info available in the via the php-business-sdk?  I have a need to query Ad Insights on deleted ads and I was hoping to add a filter to my query for active ads similar to this:

```php
$params = [
   'level' => 'ad',
      'action_breakdowns' => ['action_type'],
         'filtering' => [
          [
            'field' => 'action_type', 'operator' => 'IN', 'value' => ['offsite_conversion', 'link_click']
          ],
          [
            'field' => 'ad.delivery_info', 'operator' => 'IN', 'value' => ['active', 'archived']
          ]
      ]
]
```
I keep getting the "Invalid Parameter" error message from the API.  Is this due to having the level set to "ad" ?
