### ISSUE TITLE
how i can get image id ?

### ISSUE THREAD

**Issue by AkashkumarDev** [facebook/facebook-python-ads-sdk#271]
how i can get image id ?

here is code, for uploading image to Facebook

    image = AdImage(parent_id=('act_%s' % ad_account_id))
    image[AdImage.Field.filename] = os.path.join(app.config['UPLOAD_FOLDER'], filename)
    image.remote_create()

i can get image_hash through

    image[AdImage.Field.hash]

but not image id 

i tried
  
   image[AdImage.Field.id]

but it's blank

i want to delete an Uploaded image.
here https://github.com/facebook/facebook-python-ads-sdk/issues/151#issuecomment-198107891
mentioned `image_id`, but to get this value ?

**Comment by cloudxu** [comment]
Do you want to get ids in code or adjust adhoc?

We have GraphAPI to get adimages object the default fields are id and hash
act_[adaccount_id]/adimages

And you shall see the corresponding SDK code to do that too.

Let me know if you have more problem with that.

**Comment by AkashkumarDev** [comment]
works, now i have image id but still can't delete uploaded image

code

        image = AdImage('%s:%s' % (ad_account_id, image_hash), parent_id=('act_%s' % ad_account_id))
        image.remote_delete(params={AdImage.Field.hash: image_hash})


Error I'm getting

        Message: Call was not successful
        Method:  DELETE
        Path:    https://graph.facebook.com/v2.8/418334441581252:1ca0429ea7ae4d8f5f16a95e5155187e/
        Params:  {'hash': '1ca0429ea7ae4d8f5f16a95e5155187e'}

       Status:  404
       Response:
       {
          "error": {
          "fbtrace_id": "HWWdk1iagaN",
          "type": "OAuthException",
          "message": "(#803) Some of the aliases you requested do not exist:             418334441581252:1ca0429ea7ae4d8f5f16a95e5155187e",
           "code": 803
         }
      }
