### ISSUE TITLE
How to filter on video views at an ad level?

### ISSUE THREAD

**Issue by NabeelahB** [facebook/facebook-python-ads-sdk#273]
Hi,
I am trying to filter Ads having more than 100 video views. But I dont understand what field should be used in the filtering condition.

Regards,
Nabeelah

**Comment by lintaocui** [comment]
Hi, @NabeelahB thank you for reporting the issue. For Ads API SDK, filtering by video views is not supported now. 

There is an workaround:
get ads insights at ad level, select video engagement columns, then and from the report you can filter by video views
<img width="1420" alt="screenshot 2016-11-17 13 31 02" src="https://cloud.githubusercontent.com/assets/4691181/20408454/65531f3c-acca-11e6-873a-a4d49cc00b27.png">
