### ISSUE TITLE
Class for reporting on orders (beta)

### ISSUE THREAD

**Issue by jthomm** [facebook/facebook-python-ads-sdk#275]
The `order_id_attributions` [endpoint](https://developers.facebook.com/docs/marketing-api/reporting-on-orders/v2.8) (still in beta) lacks an `adobjects` class.  Is there a plan to generate this class once the endpoint is in production?

**Comment by guxuoss** [comment]
Yes.  We normally do not include endpoints that are not 100% public.  We will include these endpoints once they are public.  Thanks for your patients.

**Comment by scottydelta** [comment]
@jthomm I am trying to use that end point but I am unable to find any documentation at all. Do you have any code snippets which use this end point(os similar) or any documentation or resource you can link me to? thanks!
