### ISSUE TITLE
Member functions for AdAccount class are not working/missing

### ISSUE THREAD

**Issue by KManiKumarReddy** [facebook/facebook-python-ads-sdk#276]
Few methods of AdAccount class hit an attribute not found error.
Specifically:

- get_connection_objects()
- get_ad_pixels()
- get_ad_conversion_pixels()

The expected behaviour is documented in [Python SDK Reference](https://developers.facebook.com/docs/marketing-api/reference/sdks/python/ad-account#adaccount-get-connection-objects--fields--params-)

I'm adding my console output below:

>>> account.get_connection_objects()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'AdAccount' object has no attribute 'get_connection_objects'
>>> account.get_ad_conversion_pixels()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'AdAccount' object has no attribute 'get_ad_conversion_pixels'
>>> account.get_ad_pixels()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'AdAccount' object has no attribute 'get_ad_pixels'

**Comment by cloudxu** [comment]
We are further investigating this issue.

**Comment by kunal3** [comment]
Still getting this error.

**Comment by KManiKumarReddy** [comment]
@cloudxu I think you need to reopen this issue
