### ISSUE TITLE
 Insights API not returning JSON format

### ISSUE THREAD

**Issue by sgickling** [facebook/facebook-python-ads-sdk#277]
The result set from calling the Marketing Insights API (v2.8) returns a non-standard JSON format which makes it difficult to work with.  Python says the object type is: <class 'facebookads.api.Cursor'>
How do I get the result set in JSON or even XML?

Example result:

[\<AdsInsights> {
    "campaign_id": "606801399xxxx",
    "campaign_name": "xxxxxxxxx",
    "date_start": "2015-01-01",
    "date_stop": "2016-12-30",
    "spend": "600"
}, \<AdsInsights> {
    "campaign_id": "606791249xxxx",
    "campaign_name": "xxxxxxxxx",
    "date_start": "2015-01-01",
    "date_stop": "2016-12-30",
    "spend": "1.45"
}]

CODE Snippet:

    def get_campaign_insights(self):
        me = AdUser(fbid='me')
        my_accounts = list(me.get_ad_accounts())
        my_account = my_accounts[0]

        fields = [
            Insights.Field.campaign_id,
            Insights.Field.campaign_name,
            Insights.Field.spend
        ]

        params = {
            'time_range': {'since': str(datetime.date(2015, 1, 1)), 'until': str(datetime.date.today())},
            'level': 'campaign',
            'export_format': 'json',
            'limit': 1000
        }

        stats = my_account.get_insights(fields=fields, params=params)
        print stats

**Comment by daphyFB** [comment]
Hi, 

Thanks for reporting SDK issues!

Yes, we return a Cursor object (which is like an iterator) because those querying APIs could have a large number of objects returned, which might hit the API limits.

You can use the "build_objects_from_response" method, or "get_one" method of the Cursor object to get some returned objects, which type should be "AdsInsights".

The Cursor class definition is here:
https://github.com/facebook/facebook-python-ads-sdk/blob/master/facebookads/api.py#L683

Please let me know if this doesn't solve your question, and/or if you have further questions or requests.

Thanks!

**Comment by sgickling** [comment]
Thanks for the reply, I really appreciate it.
By chance, can you point me to a working example?  I'm having a hard time
getting build_objects_from_response working.

Thanks,
Steve

**Comment by daphyFB** [comment]
Hi,

The build_objects_from_response is already called when
`my_account.get_insights(fields=fields, params=params)`
is called.

Since the Cursor class here is a Python iterator, you should just be able to do:

```
stats = my_account.get_insights(fields=fields, params=params)
for stat in stats:
  print stat
```

**Comment by daphyFB** [comment]
Hi, since there's no further action required for this issue, I'm going to close it. Please feel free to reopen or create other issues if you have other questions and concerns. Thanks!

**Comment by ohlaylaohoh** [comment]
insights = account.get_insights(fields=[
    AdsInsights.Field.ad_id,
    AdsInsights.Field.ad_name,
    AdsInsights.Field.impressions,
    AdsInsights.Field.spend,
    ], params={
    'level': AdsInsights.Level.ad,
    'breakdowns': AdsInsights.Breakdowns.device_platform,
    })

    for insight in insights:
        print insight



I tried what @daphyFB recommended, but the object insight is still not in JSON format. Any follow up suggestions? Thanks in advance!

**Comment by daphyFB** [comment]
Hi, yes, the insight in your code is of type AdsInsights, not json. The AdsInsights class is defined here: https://github.com/facebook/facebook-python-ads-sdk/blob/master/facebookads/adobjects/adsinsights.py

You should be able to access the fields in those objects.

**Comment by ravindranathakila** [comment]
To get campaign info: (in cases someone ends up here like I did trying to figure out how to use the Cursor objects (which lack documentation)

```
 campaigns_cursor = AdAccount("act_<id_here>").get_campaigns(
            fields=required_campaign_fields,
            params={
                Campaign.Field.effective_status: required_campaign_statuses
            })
        campaigns = [campaign for campaign in campaigns_cursor]
        for campaign in campaigns:
            print(type(campaign))
            for value in campaign:
                print(campaign[value])
```

**Comment by FBosler** [comment]
In case anybody else ends up here and needs a helping hand.

`adobject.export_all_data() `

is what you are looking for. Called on an AdsInsights object returns a standard JSON ...

**Comment by fuxiangduan** [comment]
for stat in stats:
  print(dict(stat))
