### ISSUE TITLE
custom_audience_utils.py script error

### ISSUE THREAD

**Issue by neeruks** [facebook/facebook-python-ads-sdk#278]
Hi
I am trying to upload custom audience using custom_audience_utils.py  and getting errors. Any usage document?
And also any sample data file(like config.json.example)?

Error message
C:\Python27\python.exe cust_audience_file_utils.py -c test --file test.txt
Traceback (most recent call last):
  File "cust_audience_file_utils.py", line 126, in <module>
    args.datatype)
  File "cust_audience_file_utils.py", line 68, in CreateCustomAudience
    audience.remote_create()
	
raise fb_response.error()
facebookads.exceptions.FacebookRequestError:

  Message: Call was not successful
  Method:  POST

**Comment by lintaocui** [comment]
could you try the following data, please copy and save it as .csv file
```
email,email,email,phone,phone,phone,madid,fn,ln,zip,ct,st,country,dob,doby,gen,age,uid
elizabetho@fb.com,olsene@fb.com,eolsen@fb.com,1-(650)-561-5622,1-(650)-782-5622,1-(650)-888-5622,AECE52E7-03EE-455A-B3C4-E57283966239,Elizabeth,Olsen,94046,Menlo Park,CA,US,10/21/68,1968,F,48,1234567890
andrewj@fb.com,jamisona@fb.com,ajamison@fb.com,1-(212) 736-3100,1-(212) 523-3100,1-(212) 123-3100,BEBE52E7-03EE-455A-B3C4-E57283966239,Andrew,Jamison,10118,New York,NY,US,10/17/78,1978,M,38,1443637309
```
Tip: I got the custom audience sample file from Ads Manager -> All Tools -> Assets -> Audiences -> Create Audiences -> Custom Audience -> Custom File -> Choose a file or copy and paste data -> Download file template
