### ISSUE TITLE
UserWarning when passing nested fields to AdAccount.get_ads()

### ISSUE THREAD

**Issue by HndrkMkt** [facebook/facebook-python-ads-sdk#281]
Hi all,

For a reporting solution I need to download the entire account structure with select fields for each hierarchy level. While the Graph API allows me to make a nested request such as
`https://graph.facebook.com/v2.8/act_<account_id>/ads?fields=id,name,adlabels,adset{id,name,adlabels}&access_token=<access_token>`,
I have not found a way to replicate the same logic using the SDK.

When using the same nested field declaration as in the Graph API (`adset{id,name,adlabels}`) - e.g. in
`ad_account.get_ads(field=['id', 'name', 'campaign_id', 'adlabels'])`, 
it raises a `UserWarning: ads does not allow field adset{id,name,adlabels}`. 

Is there a different way to pass such a nested request to the `fields`-argument? If not, is there a particular reason for the warning while the Graph API is perfectly fine with this type of request or is this due to the automatic creation of the code?

Thanks for the support!

**Comment by daphyFB** [comment]
Thanks for reporting Ads API SDK issues!

I'm wondering if you just ignore the warning and proceed, does it still work? (In case you've turned STRICT_MODE to True already, please change it back here: https://github.com/facebook/facebook-python-ads-sdk/blob/master/facebookads/apiconfig.py)

**Comment by daphyFB** [comment]
closing for now; please let us know if you have further questions. thanks!
