### ISSUE TITLE
async get_insights only returning 25 records

### ISSUE THREAD

**Issue by sgickling** [facebook/facebook-python-ads-sdk#282]
For ad insights, I switched to the python SDK async call over the curl since the curl call kept bombing (size limit maybe).  I have the async call working (snippet below) but it is only returning 25 records.  We have hundreds of ads per day, so how can I access all of them?  I don't see a way to use paging cursors with the async call.

params = {
   'level': 'ad'
   , 'date_preset': 'yesterday'
   , 'time_increment': 1
   , 'fields': fields
}
async_job = campaign.get_insights(params=params, async=True)
while async_job[AdReportRun.Field.async_percent_completion] < 100:
   ......
   async_job.remote_read()
   ......

(only returns 25 when there are hundreds per day)

Can you please help?
Thanks,
Steve

**Comment by sgickling** [comment]
Nevermind... I figured out that the return type is a iterator cursor type.

**Comment by VikramTiwari** [comment]
@sgickling So were you able to increase the limit? If so, how?

**Comment by jatinder85** [comment]
@VikramTiwari you can add "limit" as param to limit X no. of records per API Call. For full load, just iterate over the response which is a cursor object

**Comment by VikramTiwari** [comment]
Should have updated earlier. Yes, Just iterating over cursor object gives full load.

One small clarification though is that cursor object will make a network request for every iteration. So it ends up being a lot of small size network calls.

**Comment by andrey-legayev** [comment]
Cursor works fine, but fails with API rate limits in case of big data amount.
I'm trying to implement async request to insights with CSV report download & parsing.
