### ISSUE TITLE
Does CustomAudience.remove_users actually work?

### ISSUE THREAD

**Issue by mochawich** [facebook/facebook-python-ads-sdk#285]
I have been trying for sometime to remove users using different schemas including exact same data I provided when creating also using an EXTERN_ID. The calls are successful and I could see the both adding and removing activity on the Assets Library from Business Manager. The audience size however is not changing, even if I wait for next day.

I have a list of 700 users. I added them using this
```python
    schema = [
        CustomAudience.Schema.MultiKeySchema.extern_id,
        CustomAudience.Schema.MultiKeySchema.fn,
        CustomAudience.Schema.MultiKeySchema.ln,
        CustomAudience.Schema.MultiKeySchema.email,
        CustomAudience.Schema.MultiKeySchema.phone,
        CustomAudience.Schema.MultiKeySchema.zip,
        CustomAudience.Schema.MultiKeySchema.ct,
        CustomAudience.Schema.MultiKeySchema.country,
    ]
    fb_audience = CustomAudience('custom audience id')
    fb_audience.remove_users(schema=schema, users=raw_users, is_raw=True)
```

This is how I'm removing them
```python
    schema = CustomAudience.Schema.MultiKeySchema.extern_id
    user_ids = [user_id.hex for user_id in users_to_remove]
    fb_audience = CustomAudience('custom audience id')
    fb_audience.remove_users(schema=schema, users=user_ids, is_raw=False)
```

I keep seeing this

![](https://cl.ly/3t1F0G1V031b/Screen%20Shot%202017-02-15%20at%2014.21.13.png)

Any ideas?

**Comment by mochawich** [comment]
Another question
Is there a way to purge an audience without deleting it and creating a new one?

We have many audiences that are attached to different campaigns and we would like to populate them with completely new users. Before doing that we must first remove the old ones.

**Comment by Larsen1000** [comment]
I am having issues here as well. When i try to upload a list with externID, Facebook closes the connection.

**Comment by mochawich** [comment]
@Larsen1000 make sure you are not exceeding the batch size when uploading. For deleting, it would be even smaller as the body params got converted to url query.

I'm closing this issue as I have managed to confirm that deletion actually works. It just takes up to 7 days to show the new audience size (only when removing users though).
