### ISSUE TITLE
breakedowns doesnt works

### ISSUE THREAD

**Issue by nicoschuck** [facebook/facebook-python-ads-sdk#290]
I want the insights of my Account. Actually it works but if i set a breakdown it doesnt works. 

Here is my code:

insights = accounts[1].get_insights(fields=[
    Insights.Field.ad_name,
    Insights.Field.adset_name,
    Insights.Field.campaign_name,
    Insights.Field.unique_clicks,
    Insights.Field.impressions,
], params={
    'level': Insights.Level.ad,
    'breakdown': Insights.Breakdown.age,
    'date_preset': Insights.Preset.last_30_days,
   #i know that last 30days is the default too!!!
})

The result is the same like without breakdowns. Here is an example:

[<AdsInsights> {
    "ad_name": "...",
    "adset_name": "...",
    "campaign_name": "...",
    "date_start": "2017-02-05",
    "date_stop": "2017-03-06",
    "impressions": "59298",
    "unique_clicks": "480"
},

But i expacted something like:

[<AdsInsights> {
    "ad_name": "...",
    "adset_name": "...",
    "campaign_name": "...",
    "date_start": "2017-02-05",
    "date_stop": "2017-03-06",
    13-17:{
    "impressions": "17216",
    "unique_clicks": "240"
    }
   18-25:{
    "impressions": "19298",
    "unique_clicks": "280"
    }
    ...
},

A further issue is that i can´t choose time breakdowns like day or month.
On the developer page of facebook i can´t find any solution for that so i hope someone from here can help me.

**Comment by ddd-malay** [comment]
There is typo: breakedown

**Comment by nicoschuck** [comment]
fixed but still not working

**Comment by JiamingFB** [comment]
This is fixed by latest release.
