### ISSUE TITLE
Account spend_cap should be integer

### ISSUE THREAD

**Issue by lucascosta** [facebook/facebook-python-ads-sdk#291]
It seems there's a mismatch between the `spend_cap` type generated code and the api.
I tried updating an `AdAccount` using a float (https://github.com/facebook/facebook-python-ads-sdk/blob/master/facebookads/adobjects/adaccount.py#L151) but I received an error message:

```
FacebookRequestError:

  Message: Call was not successful
  Method:  POST
  Path:    https://graph.facebook.com/v2.8/XXXXXXXXXXXXXXXXXX/
  Params:  {'spend_cap': 10000.0}

  Status:  400
  Response:
    {
      "error": {
        "message": "(#100) Param spend_cap must be an integer",
        "code": 100,
        "type": "OAuthException",
        "fbtrace_id": "GxvhGZOq0nX"
      }
    }
```

**Comment by cloudxu** [comment]
@lucascosta, you are actually calling to a campaign group object model, not adaccount. So this is expected. I agree we have an API inconsistency for the account level spent cap (float) and campaign group spend cap (int). We will discuss it internally and get a fix in API.
