### ISSUE TITLE
request too much data

### ISSUE THREAD

**Issue by nicoschuck** [facebook/facebook-python-ads-sdk#294]
If i use time_increment on ad level i get an error. Also if i set a limit of 1 the request doesnt works.
This is my request:

```
account = AdAccount("act_***")
insights = account.get_insights(fields=[
        Insights.Field.account_id,
	Insights.Field.ad_name,
	Insights.Field.adset_name,
	Insights.Field.campaign_name,
	Insights.Field.unique_clicks,
	Insights.Field.impressions,
        Insights.Field.spend,
	Insights.Field.clicks,
	Insights.Field.estimated_ad_recallers,
	Insights.Field.inline_link_clicks,
	Insights.Field.reach,
	Insights.Field.video_10_sec_watched_actions,
	Insights.Field.video_p100_watched_actions,
	Insights.Field.actions,
	Insights.Field.action_values,
], params={
    'level': Insights.Level.ad,
    'date_preset': Insights.Preset.last_30_days,
    'time_increment': 1,
    'action_attribution_windows': [Insights.ActionAttributionWindows.value_1d_view,
                                   Insights.ActionAttributionWindows.value_7d_view,
                                   Insights.ActionAttributionWindows.value_28d_view,
                                   Insights.ActionAttributionWindows.value_1d_click,
                                   Insights.ActionAttributionWindows.value_7d_click,
                                   Insights.ActionAttributionWindows.value_28d_click],
})
```
Everytime i get following error:

> Status:  500
>   Response:
>     {
>       "error": {
>         "message": "Please reduce the amount of data you're asking for, then retry your request", 
>         "code": 1
>       }
>     }
An smaller adAccounts my request works. I have to be possible for bigger accounts too.
How can i request all data so that i can dynamical loop thorugh them?

**Comment by cloudxu** [comment]
I think probably your data is indeed large. Please see the documentation on time_increment:

https://developers.facebook.com/docs/marketing-api/reference/ad-account/insights/

Basically the smaller the number is, the more data you are downloading.

You can also query for less days in date_preset to cut down the size of the response.

**Comment by nicoschuck** [comment]
Yes i allready know the issue. But actually the data is not realy large. How can i fix this problem dynamical. I could request day by day? And what I could do if a diffrent account has more data at one day. 
Looks not professional for me. I believe it is not unusually to request as much data as me. So maybe the range of data depends on my access level?

**Comment by zgrannan** [comment]
I encountered this same problem. It looks like the error is returned for large amounts of data in the range of the entire `date_preset`, even when the `limit` is set to a small value (such as 1). 

You can use an Asynchronous job to request this data:
https://developers.facebook.com/docs/marketing-api/insights/async/v2.8

**Comment by nicoschuck** [comment]
thank you a lot. i will try it soon.
I detected the same problem if i use a limit by 1. But python use pagination like the graph explorer. If i use the same query at the explorer i will get a result. 
So i believe it have to exist an official clearly solution for the problem.
And i don't understand why this issue is closed because i got the same answer like i allready wrote in the headline: i request too much data. I hope someone can reopen this case.
Nethertheless i´m realy grateful for the help!

**Comment by smar10** [comment]
Same error here ! If I choose an time_increment 1 for lifetime period , I get an 500 error status.

On graph explorer, I get ~ 3000 records. The maximum of records I can get in python is about 600.

Any new about this issue ?

**Comment by kulichevskiy** [comment]
Hi guys. I have the same issue, but in my case I'm asking a data for only a single date on the account level. So the result should be just a single row with 3 numbers. Still too much data for Facebook:

`Message: Call was not successful
  Method:  GET
  Path:    https://graph.facebook.com/v3.1/act_123456789/insights
  Params:  {'time_range': '{"since":"2018-09-25","until":"2018-09-25"}', 'fields': 'impressions,spend,clicks,campaign_name', 'filtering': '[{"field":"ad.spend","operator":"GREATER_THAN","value":0},{"field":"ad.impressions","operator":"GREATER_THAN","value":0}]', 'limit': 1, 'level': 'account'}

  Status:  500
  Response:
    {
      "error": {
        "message": "Please reduce the amount of data you're asking for, then retry your request", 
        "code": 1
      }
    }`

Any advice?

**Comment by jingping2015** [comment]
Hey, thanks for your comment! This is actually an api issue. Please report the issue on Devsite Bug Report channel: https://developers.facebook.com/support/bugs/ Thanks!
