### ISSUE TITLE
examples/read_objects.py is broken: ImportError: cannot import name AdCampaign

### ISSUE THREAD

**Issue by uppercasebrands** [facebook/facebook-python-ads-sdk#297]
python read_objects.py -h
Traceback (most recent call last):
  File "read_objects.py", line 27, in <module>
    from facebookads.objects import (
ImportError: cannot import name AdCampaign

Seems like version 2.8 changed AdCampaign to Campaign.

There are a few more bugs in read_objects.py regarding deprecated names and methods.

**Comment by advance512** [comment]
LGTM

**Comment by daphyFB** [comment]
the fix has been merged.
