### ISSUE TITLE
Batch remote creation does not properly encode NoneType in id field

### ISSUE THREAD

**Issue by grantt** [facebook/facebook-python-ads-sdk#30]
When adding a remote_create call to a batch an error occurs where the None value for id cannot be properly quoted by `urllib.parse.quote`. At this point in the `add` call the params should already be valid JSON thanks to `_top_level_param_json_encode`. Unfortunately, this function only attempts to apply `json.dumps` to a value if it is an instance of `collections.Mapping`, `collections.Sequence`, or `bool` and is not an instance of `six.string_types`. `None` evades this conditional and is left unmodified in the parameters leaving it to fail when it is passed later as a parameter.

**Comment by facebook-github-bot-9** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by rituparnamukherjee** [comment]
I am going to close this one out. Since we have updated the batch call logic. If you still see this, feel free to reopen.
