### ISSUE TITLE
ImportError: No module named 'facebookads.adobjects.adstudy'

### ISSUE THREAD

**Issue by fai-huntrakool** [facebook/facebook-python-ads-sdk#307]
Hey Guys

I tried to create split test for my campaign. However, I found there's no module named 'facebookads.adobjects.adstudy' for the the version (2.8)

**Comment by uppercasebrands** [comment]
Can you give the snippet of the code that gives the error, and from where in the directory tree you are trying to run it from? 

As for me, in the current HEAD (2.8.2), from the parent directory, when I type the commands below from the python interpreter, all of them work:
$ python
Python 2.7.10 (default, Feb  6 2017, 23:53:20)
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import facebookads
>>> import facebookads.adobjects
>>> import facebookads.adobjects.adstudy
>>> from facebookads.adobjects.adstudy import AdStudy

**Comment by fai-huntrakool** [comment]
Thanks. I'd installed facebookads month ago with the version 2.8.1 and I've just found that it didn't contain any of adstudy.py inside. Therefore, I uninstalled the old package and tried again with 'python setup.py install'.

Now it works well.
