### ISSUE TITLE
specs.py contains wrong import 

### ISSUE THREAD

**Issue by Odelya** [facebook/facebook-python-ads-sdk#310]
`from facebookads.objects import AbstractObject` in specs.py 

The import is broken - there is no such folder objects

**Comment by uppercasebrands** [comment]
#305 fixes the issue.

**Comment by Federico-Comesana** [comment]
@uppercasebrands you're right. #305 PR has **Cla Signed** label right now. 

Do you have an estimation of when this will be merged with master and published to be downloaded using pip?

**Comment by daphyFB** [comment]
Thanks for reporting Ads API SDK issues. #305 has been merged! Please feel free to reopen the issue if it still doesn't work for you. Thanks!
