### ISSUE TITLE
Outbound Clicks

### ISSUE THREAD

**Issue by Stefflan00** [facebook/facebook-python-ads-sdk#311]
I wonder if it is possible to get outbound clicks via the api?

![screenshot 2017-04-24 23 22 20](https://cloud.githubusercontent.com/assets/4007440/25359311/0012b14e-2945-11e7-9c7d-46cf11d6be38.png)

**Comment by JiamingFB** [comment]
Hi @Stefflan00, the feature is still not publicly available yet. Please stay tuned about API updates. Thanks!
