### ISSUE TITLE
ImportError: cannot import name objects

### ISSUE THREAD

**Issue by PATAPOsha** [facebook/facebook-python-ads-sdk#314]
trying to run example code:
````
from facebookads.api import FacebookAdsApi
from facebookads import objects

FacebookAdsApi.init(my_app_id, my_app_secret, my_access_token)
me = adobjects.AdUser(fbid='me')

Traceback (most recent call last):
  File "C:/Users/lolo/PycharmProjects/fbads/sss.py", line 2, in <module>
    from facebookads import objects
ImportError: cannot import name objects
````
facebookads  v. 2.9.1, installed trough pip on python 2.7

**Comment by md-contratado** [comment]
it is "adobjects" now

**Comment by uppercasebrands** [comment]
Take a look at #305, especially https://github.com/facebook/facebook-python-ads-sdk/pull/305/files. You can find how to use adobjects correctly in that PR.

**Comment by JiamingFB** [comment]
the objects.py file is deprecated and removed. please use the objects in adobjects folder.
