### ISSUE TITLE
ImportError: cannot import name objects

### ISSUE THREAD

**Issue by prodouble** [facebook/facebook-python-ads-sdk#315]
from facebookads import objects
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name objects

Any idea why this happened? Thanks a lot!

**Comment by liuzhan001st** [comment]
Same problem with you. I have to degrade to version 2.8.1 to avoid this problem, however, a "You are calling a deprecated version of the Ads API" exception could be thrown.

**Comment by liuzhan001st** [comment]
After looking into the code, i found that the file 'objects.py' is deprecated. 
You can try something like this instead:
from facebookads.adobjects.adaccount import AdAccount
and maybe your problem will be fixed.

**Comment by uppercasebrands** [comment]
Same as Issue #314. Take a look at https://github.com/facebook/facebook-python-ads-sdk/pull/305/files. You can find how to use adobjects correctly in that PR.

**Comment by JiamingFB** [comment]
objects.py is deprecated. please use adobjects.xxxx instead

**Comment by prodouble** [comment]
Thanks!
