### ISSUE TITLE
Bug: Max 100 activities retrieved from account

### ISSUE THREAD

**Issue by lfiaschi** [facebook/facebook-python-ads-sdk#317]
There is a bug when calling the `get_activies` function from the account object: the max number of retrieved activities is always 100 irrespective of the time range. 

Python API v2.9.1:

```python
from facebookads.adobjects.adaccount import AdAccount
account = AdAccount(account_id)
res= account.get_activities(params={'fields' ['actor_name,extra_data,event_time,object_name,translated_event_type,application_name']
                              })
print(len(res)) #will print 100
```
However, when using the normal rest API (paginating the results) I can get all the activities, which hints that this is a bug of the way this python API does pagination.

REST API:

```python
path = 'https://graph.facebook.com/v2.8/{}/activities?fields=actor_name,extra_data,event_time,object_name,translated_event_type,application_name&access_token={}'.format(account_id, token)
result = list()

while True:

    r= requests.get(path)
    r= r.json()
    
    result.extend(r['data'])

    if 'paging' in r and 'next' in r['paging']:
        path=r['paging']['next']
    else:
        break
print(len(result)) # Will print 256 for the account I am running this test on
```

This bug appears with all accounts which have more than 100 activities in the default time range.

**Comment by JiamingFB** [comment]
Hi @lfiaschi ,

The API always returns 100 activities for one API call, and we do auto-fetching for paginated response in the Cursor object. You can see detailed implementation in https://github.com/facebook/facebook-python-ads-sdk/blob/master/facebookads/api.py#L687

This means that if you loop over the Cursor, you'll get the right number of total activities. What happens is that it will automatically send another API call to fetch more objects if you have reached the end of the current queue (100 activities). However, this also means the len() function of Cursor only reflects the number of objects in the current queue, and it does not correctly reflect the total number of activities.
