### ISSUE TITLE
How to get data from facebook analytics ?

### ISSUE THREAD

**Issue by hueanhpt** [facebook/facebook-python-ads-sdk#332]
Please help me, how to get data from facebook analytics?

**Comment by daphyFB** [comment]
Hi, do you mean https://analytics.facebook.com/?

**Comment by hueanhpt** [comment]
Hi daphyFP. Yes, I want to get UNIQUE USERS, APP INSTALLS, NEW USERS,... ect metrics in Facebook Analytics. Please help me.

**Comment by daphyFB** [comment]
Hi, Analytics is not part of Ads SDK. You can follow this help page to get started with Analytics:
https://www.facebook.com/help/analytics

Thanks!
