### ISSUE TITLE
(#17) User request limit reached" error

### ISSUE THREAD

**Issue by dhanrajvr** [facebook/facebook-python-ads-sdk#333]
when trying to get ad insights, i am getting this error. any idea?

**Comment by uppercasebrands** [comment]
@dhanrajvr You are most likely hitting the API request limit for calls using a 'user' object. There is more info here: https://developers.facebook.com/docs/marketing-api/api-rate-limiting. When we hit this limit, we follow this suggestion in that page "Switch to the other ad accounts and come back to this account later." In other words, we use a different ad account for the calls for a while and switch back to the original one.

**Comment by daphyFB** [comment]
Thanks @uppercasebrands for answering :)
Please let us know if there's any further question!
