### ISSUE TITLE
account.get_ad_sets.load_next_page() Response time Unstable

### ISSUE THREAD

**Issue by aisir** [facebook/facebook-python-ads-sdk#337]
hi,
  I crawl one page adsetsinfo by account.get_ad_sets.load_next_page(), different Response time  each crawl, and page limit 10-100, response-time better <5s ,worse >20s, about ten thousand requests per hour,
 in my facebook apps dashboard ,average response time about 400ms, my app code in us-west-2 using aws Elastic Beanstalk
 how can reduce response time?
thanks

**Comment by daphyFB** [comment]
Thanks for reporting Ads API SDK issues.

There are lots of factors which may affect the response time; SDK itself is not the critical part. We can redirect this issue to the API team.

If this is an issue that blocks your application, please file a bug against Ads API (marketing API) to get more dedicated support resources.

Thanks!
