### ISSUE TITLE
parent_id as a parameter of constructor is being deprecated.

### ISSUE THREAD

**Issue by pita2k** [facebook/facebook-python-ads-sdk#339]
remote_create needs the parent_id, so I don't get why this warning pops up,
        params = {} if not params else params.copy()
        params.update(self.export_all_data())
        request = None
        if hasattr(self, 'api_create'):
            request = self.api_create(**self.get_parent_id_assured()**, pending=True)
        else:
            request = FacebookRequest(
                node_id=**self.get_parent_id_assured()**,
                method='POST',
                endpoint=self.get_endpoint(),
                api=self._api,
                target_class=self.__class__,
                response_parser=ObjectParser(
                    reuse_object=self
                ),
            )

**Comment by rorynelsonscott** [comment]
We're getting the same warning. All of the documentation and examples point to the use of parent_id. Would love an update on the expected implementation.

**Comment by pita2k** [comment]
you can use my fork
https://github.com/pita2k/facebook-python-ads-sdk

**Comment by guxufb** [comment]
We are depreciating creation with parent_id.  We are seeing multiple endpoints that can create the same type of object.  We do not have good ways to decide which one we should use if you are creating new object with parent_id.  Moving forward, please instantiate the parent object with the parent_id and call create_XXX function to create the object you want.

**Comment by dmk23** [comment]
Could you clarify what EXACTLY are we supposed to use instead of `parent_id`?

Right now this deprecation warning only creates confusing without a clearly explained migration path...

**Comment by stacybot123** [comment]
Any update on this?

**Comment by dmk23** [comment]
@guxufb I tried to apply your suggestion and it doesn't make sense for us

`create_XXX` functions of the parent objects, e.g. `create_ad` perform the actual creation operation with API. However, the constructor simply instantiates the object. In many cases, we need to instantiate objects without creating them, so this suggested change makes no sense for us.

For now just suppressing the warnings by replacing `parent_id=xxx` in the constructor to subsequent call to set the object's property, that the constructor does: `_parent_id=xxx`

However, are you planning to remove this `_parent_id` property too? What would replace it?

**Comment by dan-rally** [comment]
Could we please have an update on best practice? How, for example, should the following be adapted going forward:

    $campaign = new Campaign(null, $adAccount->id);

    $campaign->setData([
        CampaignFields::NAME => 'Campaign Name',
        CampaignFields::OBJECTIVE => CampaignObjectiveValues::LEAD_GENERATION,
    ]);

    $campaign->create([
        Campaign::STATUS_PARAM_NAME => Campaign::STATUS_PAUSED,
    ]);

**Comment by Hikaon** [comment]
`      campaign = Campaign()
        campaign.update({
            "_parent_id": "%insert_id_here%",
            Campaign.Field.name: name,
            Campaign.Field.objective: objective,
            Campaign.Field.status: status
        })`

**Comment by hshdy** [comment]
I also have this problem,when i use audience.remote_create()，has like this warning：
WARNING:root:parent_id as a parameter of constructor is being deprecated.
