### ISSUE TITLE
AdAccountGroup does not exist

### ISSUE THREAD

**Issue by diego-pedroza** [facebook/facebook-python-ads-sdk#342]
Getting error
adobjects\helpers\adaccountusermixin.py line 22, in <module>
from facebookads.adobjects.adaccountgroup import AdAccountGroup
ImportError: No module named 'facebookads.adobjects.adaccountgroup'

**Comment by cloudxu** [comment]
Thanks for raising this issue. It is a bug in our SDK and we have fixed it in:

https://github.com/facebook/facebook-python-ads-sdk/commit/91552376adec3560e58ec1c98d039e37af2b6cf0#diff-a8ebbb464e43cdf39644a1331f77117b

Please pull the latest revision from our repo.
