### ISSUE TITLE
Import Error on specs.py

### ISSUE THREAD

**Issue by diego-pedroza** [facebook/facebook-python-ads-sdk#343]
On file facebookads/specs.py there's an import error

Line 26:
from facebookads.objects import AbstractObject
Have to change to:
from facebookads.adobjects.abstractobject import AbstractObject

**Comment by pita2k** [comment]
Same issue,
they fixed it in a commit,

but the pip package is still outdated

**Comment by cloudxu** [comment]
Thanks for you feedback. Yes, it is fixed in

https://github.com/facebook/facebook-python-ads-sdk/commit/6f56165935b3a61c136c6717522f65cfe27aaa46#diff-8af0cfa28f9e229fa29d41e5635463f7

the pip package may be old and we will update it shortly.
