### ISSUE TITLE
cannot import name AdUser 

### ISSUE THREAD

**Issue by JoshHatfield** [facebook/facebook-python-ads-sdk#345]
I installed the latest version of the SDK today

changed objects to adobjects following recent api changes

Now I cannot import the AdUser module. I get the following error code

Traceback (most recent call last):
  File "C:\Users\semetrical\Documents\Clients\FlexiOffices\Flexioffice Tools\Flexioffices Dynamic Facebook ads\fbConnect.py", line 4, in <module>
    from facebookads.adobjects import AdUser
ImportError: cannot import name AdUser

This is the code
`
from facebookads.api import FacebookAdsApi
from facebookads import adobjects
from facebookads.adobjects import AdUser

my_app_id="dummyVariable"
my_app_secret='dummySecret"
my_access_token="dummyToken"
fbidFacebookAdsApi.init(my_app_id, my_app_secret, my_access_token)

me = AdUser(fbid='me')
my_account = me.get_ad_accounts()[0]
`

Anyone else have this issue?

**Comment by uppercasebrands** [comment]
@JoshHatfield AdUser has been renamed to AdAccountUser. You can do
`from facebookads.adobjects.adaccountuser import AdAccountUser`

Also, the current-and most recent- pip package version 2.9.1 is partially broken. You should upgrade your facebookads package from github repo. From your commandline, try:

`pip install --upgrade git+https://github.com/facebook/facebook-python-ads-sdk.git`

**Comment by JoshHatfield** [comment]
Thanks for this

Everything imports correctly now
