### ISSUE TITLE
read_objects Example Broken #2

### ISSUE THREAD

**Issue by ProsperousHeart** [facebook/facebook-python-ads-sdk#348]
Issue 1:  #331 

Issue 2 is that after changing
```
from facebookads.objects import (
    AdUser,
    Campaign,
)
```
to
```
from facebookads.adobjects import (
    AdUser,
    Campaign,
)
```
the following error is received:
```
Traceback (most recent call last):
  File "test.py", line 27, in <module>
    from facebookads.adobjects import (
ImportError: cannot import name AdUser
```

**Comment by uppercasebrands** [comment]
@ProsperousHeart I think this is the same issue as #345.

AdUser has been renamed to AdAccountUser. You can do
from facebookads.adobjects.adaccountuser import AdAccountUser

Also, the current-and most recent- pip package version 2.9.1 is partially broken. You should upgrade your facebookads package from github repo. From your commandline, try:

`pip install --upgrade git+https://github.com/facebook/facebook-python-ads-sdk.git`

**Comment by guxufb** [comment]
Thanks @uppercasebrands for the answer!

The issue of 2.9.1 pip is known and being tracked.  We will fix it soon together with other fixes.  Please use the repo version for now and sorry for the inconvenience.
