### ISSUE TITLE
Lookalike creation fails when using multiple countries

### ISSUE THREAD

**Issue by alvaro-rm** [facebook/facebook-python-ads-sdk#350]
When I try to generate a lookalike audience in multiple countries, it fails. It says:

>   Status:  400
>   Response:
>     {
>       "error": {
>         "type": "OAuthException",
>         "error_subcode": 1713089,
>         "message": "(#2654) Invalid Lookalike Country:  cannot be recognized as a valid country for creating lookalikes, please verify the format.",
>         "fbtrace_id": "Ap2VUJwZ2Lg",
>         "code": 2654
>       }
>     }

This is the code:

```
lookalike_params = {
                CustomAudience.Field.name: 'the name',
                CustomAudience.Field.subtype: CustomAudience.Subtype.lookalike,
                CustomAudience.Field.origin_audience_id: "34342343",
                CustomAudience.Field.lookalike_spec: {
                    'starting_ratio': 0.01,
                    'ratio': 0.02,
                    'target_countries': ['US', 'GB']
                },
            }
            lookalike = ad_account.create_custom_audience(params=lookalike_params)

```

**Comment by daphyFB** [comment]
Hi, please take a look at the marketing API document here:
https://developers.facebook.com/docs/marketing-api/lookalike-audience-targeting/v2.9

Under the "Custom Audience Lookalike" section, you can see that for the lookalike_spec, there is no "target_countries". You can use country for single country, or location_spec->countries.
