### ISSUE TITLE
pixel.get('code') returns None after creation

### ISSUE THREAD

**Issue by vincentwhales** [facebook/facebook-python-ads-sdk#354]
fb_pixel = fb_adaccount.create_ads_pixel(params={ AdsPixel.Field.name: 'Pixel' })
      code = fb_pixel.get('code')

After I have successfully created a pixel, why is fb_pixel.get('code') `None`? 

Must I reload the object by calling 

      fb_pixel = fb_adaccount.create_ads_pixel(params={ AdsPixel.Field.name: 'Pixel' })
      fb_pixel = fb_adaccount.get_ads_pixels(fields=[AdsPixel.Field.code])[0]
      code = fb_pixel.get('code')

**Comment by daphyFB** [comment]
Thanks for reporting Ads API SDK issues!

When you create a pixel, the return response only contains its created ID and nothing else, and thus you won't be able to get any other information from the direct response of "create_ads_pixel".

So yes, you need to reload the object by calling get_ads_pixels if you want any information other than the id.

Please feel free to reopen the issue if you have further questions!
