### ISSUE TITLE
Where is facebookads.objects?

### ISSUE THREAD

**Issue by leonardo-beetech** [facebook/facebook-python-ads-sdk#355]
I'm having issues with importing facebookads.objects, isn't it missing?

**Comment by uppercasebrands** [comment]
@leonardo-beetech It was replaced by `facebookads.adsobjects`  with the version2.9 update. For example, if you want to import AdAccount, you can do:
`from facebookads.adobjects.adaccount import AdAccount`

**Comment by leonardo-beetech** [comment]
Ohh, it isn't clear in the documentation. Anyone should update it..
But really thanks, it was a great help

**Comment by daphyFB** [comment]
Thanks for reporting Ads API SDK issues! And many thanks to @uppercasebrands  :)

The whole objects.py was manually created and was marked for deprecating for few versions. As @uppercasebrands mentioned, please use adsobjects instead, which is auto-generated and should be better aligned with Facebook marketing API.

As for the documentation, we're currently working on a better communication channels for all of Ads API developers. Thanks for your patience!
