### ISSUE TITLE
You are calling a deprecated version 

### ISSUE THREAD

**Issue by julgq** [facebook/facebook-python-ads-sdk#356]
"message": "(#2635) You are calling a deprecated version of the Ads API. Please update to the latest version: v2.9.", 
        "code": 2635, 
        "type": "OAuthException",

**Comment by uppercasebrands** [comment]
@julgq You should upgrade your Python facebookads package from github repo. From your commandline, try:

`pip install --upgrade git+https://github.com/facebook/facebook-python-ads-sdk.git`

**Comment by cloudxu** [comment]
@julgq, @uppercasebrands has the right answer, the current active api version is 2.9 with 2.8 is phasing out.

**Comment by guxufb** [comment]
v2.8 is still active in API.  You app might be created after v2.9 release.  Thus, the lowest API version you can use it v2.9 rather than v2.8.
