### ISSUE TITLE
ProductAudience removed

### ISSUE THREAD

**Issue by brandonkane** [facebook/facebook-python-ads-sdk#357]
Hi there,

As several other Issues (#355, #334, #331) have commented on, the imports from facebookads.objects were removed in 2.9.  This is fine since in general they were just shortcuts to other objects.

However, in the commit where objects.py was removed by @xiaotchen , at least one class was taken out that does not exist anywhere else in the package.  ProductAudience was removed here:

https://github.com/facebook/facebook-python-ads-sdk/commit/5a01e17a103df3d549bcf2edd793789cd321fab5#diff-8882fc2e00b3b6bc00a4d646574f11c4L452

Where should this class live?  I'm happy to put up a PR to add it back in.  facebookads/adobjects/productaudience.py would seem to be consistent with how other things are organized.  

Comments? Was there a reason why this class was removed?  If it was intentional there was no mention of it anywhere that I could find.

**Comment by daphyFB** [comment]
Thanks for reporting Ads API SDK issues!

The whole objects.py was deprecating, including all of these type of manually-created classes.

Every operation on product audience can be done via custom audience; product audience was a special type of custom audience anyway. You should be able to read via custom audience, and create still via adaccount product audience:
https://github.com/facebook/facebook-python-ads-sdk/blob/master/facebookads/adobjects/adaccount.py#L1837

Please feel free to reopen the issue if you have further questions.

**Comment by brandonkane** [comment]
@daphyFB The docs for creating product audiences still suggest you use the class that was deleted: https://developers.facebook.com/docs/marketing-api/dynamic-product-ads/product-audiences/v2.9.  Do you have an updated example code snippet for using the AdAccount. create_product_audience rather than the ProductAudience?

**Comment by daphyFB** [comment]
Hi @brandonkane , sorry for the outdated documentation.
We don't have an office example yet, but it should be pretty similar to the java example:

CustomAudience customAudience = new AdAccount(act_<AD_ACCOUNT_ID>, context).createProductAudience()
  .setName("Product audience")
  .setProductSetId(<PRODUCT_SET_ID>)
  .setInclusions("[{\"retention_seconds\":\"86400\",\"rule\":{\"event\":{\"eq\":\"AddToCart\"}}},{\"retention_seconds\":\"72000\",\"rule\":{\"event\":{\"eq\":\"ViewContent\"}}}]")
  .setExclusions("[{\"retention_seconds\":\"172800\",\"rule\":{\"event\":{\"eq\":\"Purchase\"}}}]")
  .execute();
