### ISSUE TITLE
LookalikeAudience Field don't have id

### ISSUE THREAD

**Issue by hongphi** [facebook/facebook-python-ads-sdk#36]
I can't create a LookalikeAudience:
lookalike = LookalikeAudience(parent_id=self.ad_account_id)
It has a error "type object 'Field' has no attribute 'id". In your API, class LookalikeAudience don't have id in the Field class. Is this a bug?

**Comment by ebzlo** [comment]
Hey @hongphi, this looks like a bug. Pushing out a fix and a test later today.

**Comment by hongphi** [comment]
Thanks @ebzlo
