### ISSUE TITLE
Feature Request: adsobject.AbstractObject to have a 'default value' for its getters

### ISSUE THREAD

**Issue by uppercasebrands** [facebook/facebook-python-ads-sdk#360]
@daphyFB @cloudxu It will be a small but relatively nice improvement if AbstractObject.getters acted more like the dictionary getter with a default value. 

Like https://docs.python.org/2/library/stdtypes.html describes, would it be okay to have get(key[, default]) return the value for key if key is in the dictionary, else default. Currently, if the key is not in the AbstractObject's dict, it returns NoneType.

If you think this makes sense, I will send you a PR. Thanks.

**Comment by guxufb** [comment]
@uppercasebrands, it looks like a good idea.  I would assume that if people did not specify the default value, the behavior will not change.  Just to ensure that this change will not break any existing code.

**Comment by uppercasebrands** [comment]
@guxufb My bad! absobject.AbstractObject inherits from Collections.MutableMapping which inherits from Collections.Mapping. The latter one provides the get method with an optional default parameter (just like standard get() method works). So my suggestion is moot, this already works. https://docs.python.org/2/library/collections.html#collections.Mapping

Thanks for commenting on my request:)
