### ISSUE TITLE
Nested query

### ISSUE THREAD

**Issue by drapadubok** [facebook/facebook-python-ads-sdk#361]
Hi, and thanks for great tool.

I'm trying to efficiently query the insights API to get the cost data over all campaigns, ad sets and ads. I tried something along these lines. 

```
campaigns = my_account.get_campaigns()
for campaign in campaigns:
    campaign.get_insights(fields=[Insights.Field.spend])
```

This works but I always hit rate limit. I was wondering if making a nested query would help? How can I make a nested query using python SDK?

**Comment by uppercasebrands** [comment]
@drapadubok You may want to look into [FacebookAdsApiBatch](https://github.com/facebook/facebook-python-ads-sdk/blob/a161f2cc4524370957c97af5bfb75259ef8208fd/facebookads/api.py#L343): Essentially you want to create a batch query, and pass this to campaign.get_insights().

**Comment by guxufb** [comment]
@uppercasebrands batch API does not let you get away from the throttling.  

@drapadubok You should pull insights at the ad account level with the right level.  Then you can get the spend information of all your campaigns in one API call.  Please search for the "levels" section in this doc.  https://developers.facebook.com/docs/marketing-api/insights/v2.9

**Comment by uppercasebrands** [comment]
@guxufb Is there a way to increase the limits on our app? Our app is still in development mode and I was wondering once we launch our app, if we could increase the limit.

**Comment by guxufb** [comment]
Development apps are heavily throttled.  You should be promoted to basic automatically if you have enough API calls.  if you are building business, it is better to get your app all the way to the standard before the official launch.  It will give you a lot more "karma" for API calls.
