### ISSUE TITLE
AdAccount.get_campaigns(params={'updated_since': 1498013480}) does not work.

### ISSUE THREAD

**Issue by uppercasebrands** [facebook/facebook-python-ads-sdk#362]
Campaigns class has "updated_time" field but I cannot filter it using updated_since param. Is this a known issue or works as intended? If so, is there a way to filter Campaigns on updated_time?

**Comment by guxufb** [comment]
updated_time filtering is not supported at the campaign level.  Please use other communication channels for API related issues.
