### ISSUE TITLE
Example on cloning an object

### ISSUE THREAD

**Issue by bschlenk** [facebook/facebook-python-ads-sdk#363]
There should be an example on how to clone an object in the examples folder. I'm trying to clone an adcreative and change a few fields, but I can't for the life of me figure out how to do it. I tried fetching an existing creative, calling `clear_id()` on it, and then `api_create(parent_id='act_<account_id>')`, but it looks like no data is actually being sent with the request.

**Comment by daphyFB** [comment]
Thanks for reporting Ads API SDK issues!

Looks like what you wanted to do was copying an ads:
https://developers.facebook.com/docs/marketing-api/reference/adgroup/copies
https://developers.facebook.com/docs/marketing-api/reference/ad-campaign/copies
https://developers.facebook.com/docs/marketing-api/reference/ad-campaign-group/copies

SDK hasn't supported copies yet; we're working on it. For now if you want to copy any ad object, please refer to the above links.

Thanks!

**Comment by veniversum** [comment]
Why is this issue closed? `copies` seem to have been introduced since API v2.10 but still isn't supported by the Py SDK. 

Is the feature still a WIP?
