### ISSUE TITLE
How to get long-lived access token?

### ISSUE THREAD

**Issue by alexvelickiy** [facebook/facebook-python-ads-sdk#370]
Could find doc about how to exchange short-lived access token for long-lived.

**Comment by TimSmith714** [comment]
Is this https://developers.facebook.com/docs/facebook-login/access-tokens/expiration-and-extension
what you were looking for?
This has been on my todo list for a couple of weeks
I've done some Facebook Login bits so far but they're not in the Python SDK. It's not too difficult when using Python Requests http://docs.python-requests.org/en/master/

**Comment by alexvelickiy** [comment]
Yeah, I meant it. Thank you, I just did it with Requests. Just was curious if this function exists in SKD.

**Comment by CT83** [comment]
@alexvelickiy Could you please link your code? I am trying to do the same

**Comment by CT83** [comment]
@alexvelickiy Oh! Nevermind, Found [it!](https://stackoverflow.com/a/30054746/7127317)
