### ISSUE TITLE
Broken examples

### ISSUE THREAD

**Issue by arpanshah29** [facebook/facebook-python-ads-sdk#373]
The examples are broken for the new version of the facebook-python-ads api that has been released. This combined with the limited documentation surrounding this library makes it very difficult to use.

**Comment by kevinqz** [comment]
Fixed two of them in the #346 Pull Request, waiting for requested changes approval.

**Comment by guxufb** [comment]
We are working on more and better examples.  We need solutions that can scale to all languages  (php, python, java and ruby for now).  We may not be able to priority the work that can only fix case by case.  PRs are welcome.
