### ISSUE TITLE
Unsupported request. Object with ID ...

### ISSUE THREAD

**Issue by MarcoPorracin** [facebook/facebook-python-ads-sdk#380]
Im trying to query the costs of my facebook campaigns with a python script. For now i think the sample code they generate for you is ok, but im getting this error:

> Unsupported get request. Object with ID 'XXX' does not exist, cannot be loaded due to missing permissions, or does not support this operation.
> And i cant figure out what im doing wrong.
> For the access token im generating one on the Marketing API Configuration.

Any idea what i skipped or did wrong?

Here is the sample code im using:

```
    from facebookads.adobjects.adaccount import AdAccount
    from facebookads.adobjects.adsinsights import AdsInsights
    from facebookads.api import FacebookAdsApi
    
    access_token = 'xxx'
    ad_account_id = 'xxx'
    app_secret = 'xxx'
    FacebookAdsApi.init(access_token=access_token)
    
    fields = [
        'today_spend',
    ]
    params = {
        'time_range': {'since':'2017-07-03','until':'2017-08-02'},
        'filtering': [],
        'level': 'campaign',
        'breakdowns': [],
    }
    print AdAccount(ad_account_id).get_insights(
        fields=fields,
        params=params,
    )
```

The app has the ad account added to it from both the app configuration and the bussiness configuration:

![imettrics_-_configuracion_-_facebook_for_developers](https://user-images.githubusercontent.com/22181136/28834710-6e5670d4-76b9-11e7-9bbe-b8da7262f8bc.png)

![administrador_comercial](https://user-images.githubusercontent.com/22181136/28834633-2e577ae6-76b9-11e7-82e8-c9c1c1f41175.png)

Here i get the access token:
![administrador_comercial](https://user-images.githubusercontent.com/22181136/28834501-cd88ce7c-76b8-11e7-83aa-a8c4b7357190.png)

![administrador_comercial](https://user-images.githubusercontent.com/22181136/28834552-ee39679e-76b8-11e7-846f-700bfb9ac7e3.png)

**Comment by guxufb** [comment]
you may want to use "act_xxxx" for ad account id.

**Comment by MarcoPorracin** [comment]
Yes, that was the problem. 

Facebook documentation is shit.
