### ISSUE TITLE
Pagination Value

### ISSUE THREAD

**Issue by ravindranathakila** [facebook/facebook-python-ads-sdk#383]
When listing objects (Campaigns for example) in an Ad Account level (such as mentioned here: https://github.com/facebook/facebook-python-ads-sdk/blob/master/examples/read_objects.py) what is the pagination value used? is it 10?

**Comment by guxufb** [comment]
you can use limit in the param.  it is not considered as valid param in the class definition as it is supported by all Facebook APIs.  It is an improvement we can add to our SDKs.
