### ISSUE TITLE
facebookads.adobjects.lookalike_spec got wrong field types for multi-country lookalike creation

### ISSUE THREAD

**Issue by simonkreienbaum** [facebook/facebook-python-ads-sdk#386]
The field type 'target_countries' doesn't exist anymore, while the 'location_spec' field is missing in this documention.

This is how I would expect to create from your documentation:

```
ad_account.create_custom_audience(params={
    'subtype': 'lookalike',
    'origin_audience_id': seed_audience_id,
    'lookalike_spec': {
        "targeting_countries": ["US", "CA"],
        "is_financial_service": False,
        "allow_international_seeds": False,
        "ratio": 0.1,
    },
})
```

But this throws an error.

Instead, this works:

```
ad_account.create_custom_audience(params={
    'subtype': 'lookalike',
    'origin_audience_id': seed_audience_id,
    'lookalike_spec': {
        "location_spec": {
            "geo_locations": {
                "countries": ["US", "CA"]
            }
        },
        "is_financial_service": False,
        "allow_international_seeds": True,
        "ratio": 0.1,
    },
})
```

https://github.com/facebook/facebook-python-ads-sdk/blob/master/facebookads/adobjects/lookalikespec.py

Refer to https://developers.facebook.com/docs/marketing-api/lookalike-audience-targeting/v2.10.

**Comment by guxufb** [comment]
The definitions of lookalike spec are different from the read (as field) and write (as param).  Due to some internal limitations, we cannot tell the type on the write path.  You should construct the call based on the documentation, rather than using LookalikeSpec.

https://github.com/facebook/facebook-python-ads-sdk/blob/master/facebookads/adobjects/customaudience.py#L205

**Comment by tosolveit** [comment]
@guxufb Is it possible to share an example, is @simonkreienbaum example fine to use for multiple countries, thanks!

**Comment by guxufb** [comment]
You basically need to read the API document and compose the json string by yourself.  We do not address API questions here.  Please go to the following group for API questions. https://www.facebook.com/groups/pmdcommunity/
