### ISSUE TITLE
async api is not functioning properly

### ISSUE THREAD

**Issue by VikramTiwari** [facebook/facebook-python-ads-sdk#389]
Anyone else experiencing issues with Async API for marketing-API/insights? All my calls are returning 500 or an error page.

![20994145_1883693571657832_2890475085448914090_n](https://user-images.githubusercontent.com/1330677/29729879-d6e85270-8992-11e7-934a-074dff975464.jpg)
![21078622_1883693278324528_8298278017939655903_n](https://user-images.githubusercontent.com/1330677/29729883-d89d98dc-8992-11e7-937e-da7d99edb17b.jpg)

**Comment by michaelwclark** [comment]
There are currently a handfull of known bugs causing issues. Search around https://developers.facebook.com/bugs

one example https://developers.facebook.com/bugs/1855933381387606/

My CI pipe is broken today in 10 places due to these backend errors of FBs end. Hang in there, they are working on it.

**Comment by VikramTiwari** [comment]
This started working late-evening yesterday.
