### ISSUE TITLE
Website Custom Audience Creation fails

### ISSUE THREAD

**Issue by cscanlin** [facebook/facebook-python-ads-sdk#41]
Creating a WCA is failing because pixel_id is not listed as a field.

Adding the text:

    pixel_id = 'pixel_id'

Under:

    class CustomAudience(AbstractCrudObject):

        class Field(object):

fixes this problem

__Edit:__
Pull Request here: https://github.com/facebook/facebook-python-ads-sdk/pull/43

**Comment by ebzlo** [comment]
Thanks for the PR @cscanlin pulling in your PR now.
