### ISSUE TITLE
async api - HTTP 500 error

### ISSUE THREAD

**Issue by VikramTiwari** [facebook/facebook-python-ads-sdk#414]
Getting 500 error while fetching data from Insights API. Contains no other data than just 500 response, not even an error message. Headers:

![screen shot 2017-11-13 at 12 11 48](https://user-images.githubusercontent.com/1330677/32746943-11dc73d0-c86c-11e7-84a5-29855fb61678.png)

**Comment by negianuj8** [comment]
#

**Comment by windsfantasy6** [comment]
Hi,
that's not related to our SDK issue. Could you file a bug here? https://www.facebook.com/help/440338062710823
Thanks!
