### ISSUE TITLE
UserWarning: adlabels does not allow field ads

### ISSUE THREAD

**Issue by mandrews** [facebook/facebook-python-ads-sdk#418]
The Python SDK does not allow adlabels to be fetched with ads, adsets, campaigns. This example:
```python
for label in self.account.get_ad_labels(fields=['ads','adsets','campaigns']):
   print(label)
```
produces the following warnings:
```
/usr/local/lib/python3.6/site-packages/facebookads/utils/api_utils.py:30: UserWarning: adlabels does not allow field ads
  warnings.warn(message)
/usr/local/lib/python3.6/site-packages/facebookads/utils/api_utils.py:30: UserWarning: adlabels does not allow field adsets
  warnings.warn(message)
/usr/local/lib/python3.6/site-packages/facebookads/utils/api_utils.py:30: UserWarning: adlabels does not allow field campaigns
  warnings.warn(message)
```

GraphAPI does allow these fields:
```bash
  curl -i -X GET \
  "https://graph.facebook.com/v2.11/act_XXX/adlabels?fields=id%2Cname%2Cads%2Cadsets%2Ccampaigns&access_token=<access token sanitized>"
```

**Comment by windsfantasy6** [comment]
Hi,
For adlabels, 'ads', 'adsets' and 'campaigns' are invalid fields. In GraphAPI, we just ignore these fields; In SDK, we check these fields are invalid and throw some warnings in this case.

**Comment by mandrews** [comment]
@windsfantasy6  these fields are **not** ignored in GraphAPI- I can clearly see them. I realize they are ignored in the SDK - I was heeding the warning in the [auto-generated code](https://github.com/facebook/facebook-python-ads-sdk/blob/master/facebookads/adobjects/adlabel.py#L30).

>This class is auto-generated.
For any issues or feature requests related to this class, please let us know on
github and we'll fix in our codegen framework. We'll not be able to accept
pull request for this class.

Example:
```
 curl -i -X GET \
  "https://graph.facebook.com/v2.11/act_XXX/adlabels?fields=id,name,ads
```
Output:
```
{
  "data": [
    {
      "id": "AD_LABEL_ID",
      "name": "NAME",
      "ads": {
        "data": [
          {
            "id": "AD_ID"
          },
   ...
```

**Comment by windsfantasy6** [comment]
Quick response:
For 'id' and 'name' fields, they are valid - https://github.com/facebook/facebook-python-ads-sdk/blob/master/facebookads/adobjects/adlabel.py#L43,
For 'ads' and other 2 fields, we will try to look into this and figure out why it is not in the 'adlabel.Field'. Thanks!

**Comment by mandrews** [comment]
@windsfantasy6 I wanted to use the above GraphQL query b/c it was the most efficient. When I use inefficient queries like `adlabel.getAds()`- I get rate limited:
https://github.com/facebook/facebook-python-ads-sdk/issues/416
