### ISSUE TITLE
AttributeError: 'str' object has no attribute 'get' on all reading methods

### ISSUE THREAD

**Issue by thenaturalist** [facebook/facebook-python-ads-sdk#437]
All get methods are not working for me anymore. Following the standard init & process as per [facebook-python-ads-sdk/examples/read_objects.py](https://github.com/facebook/facebook-python-ads-sdk/blob/4442744127f9e2d8ff16b2a9a04728a0e726e7da/examples/read_objects.py). 

Stating one example here. 

```
FacebookAdsApi.init(my_app_id, my_app_secret, my_access_token)

me = adaccountuser.AdAccountUser(fbid='me')

my_accounts = list(me.get_ad_accounts())

---------------------------------------------------------------------------
AttributeError                            
Traceback (most recent call last) in <module>()
----> 1 my_accounts = list(me.get_ad_accounts())

~/python3.6/site-packages/facebookads/adobjects/helpers/adaccountusermixin.py in get_ad_accounts(self, fields, params)
     52     def get_ad_accounts(self, fields=None, params=None):
     53         """Returns iterator over AdAccounts associated with this user."""
---> 54         return self.iterate_edge(AdAccount, fields, params, endpoint='adaccounts')
     55 
     56     def get_ad_account(self, fields=None, params=None):

~/python3.6/site-packages/facebookads/adobjects/abstractcrudobject.py in iterate_edge(self, target_objects_class, fields, params, fetch_first_page, include_summary, endpoint)
    546         )
    547         if fetch_first_page:
--> 548             cursor.load_next_page()
    549         return cursor
    550 

~/python3.6/site-packages/facebookads/api.py in load_next_page(self)
    799             'GET',
    800             self._path,
--> 801             params=self.params,
    802         ).json()
    803 

~/python3.6/site-packages/facebookads/api.py in call(self, method, path, params, headers, files, url_override, api_version)
    328 
    329         if fb_response.is_failure():
--> 330             raise fb_response.error()
    331 
    332         self._num_requests_succeeded += 1

~/python3.6/site-packages/facebookads/api.py in error(self)
    128                 self.status(),
    129                 self.headers(),
--> 130                 self.body(),
    131             )
    132         else:

~/python3.6/site-packages/facebookads/exceptions.py in __init__(self, message, request_context, http_status, http_headers, body)
     78             if 'type' in self._error:
     79                 self._api_error_type = self._error['type']
---> 80             if self._error.get('error_data', {}).get('blame_field_specs'):
     81                 self._api_blame_field_specs = \
     82                     self._error['error_data']['blame_field_specs']

AttributeError: 'str' object has no attribute 'get'
```

**Comment by leobarcellos** [comment]
Same here.

**Comment by apuayush** [comment]
it seems the object you are accessing is in json format.
use json.loads(me.get_add_accounts)

**Comment by thenaturalist** [comment]
@apuayush have you tried this yourself?

`json.loads(me.get_ad_accounts())` returns the exact same message. The method call already fails as the passed param (me) is a string I think, it's not about the output.

**Comment by apuayush** [comment]
I will have to try that was a suggestion. I will ping you if I find a correct solution.

**Comment by leobarcellos** [comment]
I'm receiving the same error on AdAccount remote_read and also get_insights.

**Comment by thenaturalist** [comment]
Can others confirm whether this is working for them or not?

**Comment by thenaturalist** [comment]
Got it to work again. It's really not intuitive and annoying. 

In case FB forces you to upload a picture for "security reasons", for the same account you created the API credentials with, the calls will fail. Once you passed this checkpoint everything is back to normal.

**Comment by nicor88** [comment]
@thenaturalist We are having the same problem. Suddenly we start to receive this error: 
<pre>if self._error.get('error_data', {}).get('blame_field_specs'):
AttributeError: 'str' object has no attribute 'get'</pre>How did you solve it in the end?

**Comment by thenaturalist** [comment]
@nicor88 Check the FB account which was used to create the token & credentials you use to make the calls. When you log into that account does FB ask you for a security check or does the account work as expected? If there is an open security check associated with the account, FB seemingly blocks API calls made with it.

**Comment by nicor88** [comment]
@thenaturalist thanks for the support. Indeed, it was an issues due to security checks.

**Comment by DiegoAgher** [comment]
I opened an issue pretty much like this in #466 since I believe there should be an official answer to it.

**Comment by DiegoAgher** [comment]
@thenaturalist how long does it take for facebook to "review" your photo?

**Comment by cscalisi** [comment]
Having the same issue I think, but when uploading offline conversions. We don't get any security notification however.
