### ISSUE TITLE
Get account from config file in custom_audience_utils.py is incorrect

### ISSUE THREAD

**Issue by Jusliang** [facebook/facebook-python-ads-sdk#46]
Should genereate account like this:
`my_account = AdAccount('act_' + config['app_act_id'])`

Otherwise, it is not working. 
Because, according to the link, https://developers.facebook.com/docs/marketing-api/custom-audience-targeting/v2.3#examples

curl request with parameter: `act_<AD_ACCOUNT_ID>`

**Comment by facebook-github-bot-9** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by rituparnamukherjee** [comment]
The 'act_id' field in config.json file should be set as 'act_<ACCOUNT_ID>'. If this is in place then the my_account generated should be appropriate. Checkout the config.json.example here -https://github.com/facebook/facebook-python-ads-sdk/blob/master/config.json.example for how to set the config properly
