### ISSUE TITLE
Is there any plan to setup integration tests?

### ISSUE THREAD

**Issue by m-vdb** [facebook/facebook-python-ads-sdk#51]
Today we encountered a business-critic issue related to our use of this SDK (see https://github.com/facebook/facebook-python-ads-sdk/issues/49).

We're thinking of implementing scripts that would test that this SDK works as expected. Also, I was wondering if you have integration tests. I'm willing to contribute to those if needed. Just say the words :)

**Comment by ebzlo** [comment]
There are integration tests :)

Update the `config.json` file and run
python -m facebookads.test.integration

Also we have
python -m facebookads.test.docs (which needs to be updated to latest still)

It effectively powers this page:
https://www.facebookmarketingsdks.com/docs/python

By running every method and checking that nothing is failing.

Also if you want to add more integration tests, feel free by all means :)

**Comment by m-vdb** [comment]
good to know @ebzlo thanks! I'll check them and add more if needed. Sorry about that, I didn't read the README thoroughly...
