### ISSUE TITLE
Encoding issue when calling API

### ISSUE THREAD

**Issue by m-vdb** [facebook/facebook-python-ads-sdk#55]
Hi there,

We encountered encoding issues when trying to send Swedish or French text. We might want to adapt [the following code](https://github.com/facebook/facebook-python-ads-sdk/blob/master/facebookads/api.py#L386-L387):
```
        if params:
            params = _top_level_param_json_encode(params)
            keyvals = ['%s=%s' % (key, urllib.parse.quote(value))
                       for key, value in params.items()]
            call['body'] = '&'.join(keyvals)
```

At first, we thought (as always with encoding) that we should do it ourselves before handing data to the Api, but the issue is that when reading data, the api will return `unicode` object instead of `basestring` object, hence it makes it difficult to handle every situation. For instance:
```
data = {...}
data = {key: value.encode("utf-8") for key, value in data.iteritems()}
creative = AdCreative().remote_create(params=data)  # this one will work
creative.remote_read(fields=["name", ...])  # let's say the name contains utf-8
adgroup_name = "Adgroup for " + creative["name"]  # here we have utf-8
adgroup_data = {"name": "adgroup_name", ...}
adgroup = AdGroup().remote_create(params=adgroup_data)  # this call will fail
```
The exception will be `KeyError: u'\xe9'` when calling the `urllib.parse.quote` method.

The fix is fairly easy and easily testable, let me know if you're interested in a PR, I can provide it quickly

**Comment by m-vdb** [comment]
cc @ebzlo

**Comment by ebzlo** [comment]
Yes, let's chat over the PR :)

**Comment by m-vdb** [comment]
cool thanks :)

**Comment by facebook-github-bot-9** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.
