### ISSUE TITLE
AdUser.get_ad_account doesn't flow api instance to AdAccount

### ISSUE THREAD

**Issue by dylanlingelbach** [facebook/facebook-python-ads-sdk#66]
When I create an `AdUser` with a specific api instance and then call `get_ad_account` on that instance the api instance does not flow to the created `AdAccount`.

Here is a test case that reproduces this issue:

```python
    app_id = config['app_id']
    app_secret = config['app_secret']
    access_token = config['access_token']
    def test_get_ad_account_from_ad_user():
        assert FacebookAdsApi.get_default_api() == None # Ensure the default api is not set
        session = FacebookSession(
            app_id,
            app_secret,
            connection.access_token,
        )
        api = FacebookAdsApi(session)
        me = AdUser(fbid='me', api=api)
        ad_account = me.get_ad_account()
        assert ad_account.get_api() == api
```

**Comment by dylanlingelbach** [comment]
This seems to be more general than the specific case I have above. It seems like any call that creates an object does not flow the api instance.

I am using version 2.3.3 of this library.

**Comment by ebzlo** [comment]
Hey @dylanlingelbach, we don't flow the api object in the manner you're describing (but that might be a good PR). The flow you're using would require the following call after you instantiate the `FacebookAdsApi` object:

```
api = FacebookAdsApi(session)
FacebookAdsApi.set_default_api(api)
```

Alternatively, you can skip creating the session and creating the `FacebookAdsApi` object by doing the following:

```
api = FacebookAdsApi.init(app_id, app_secret_access_token)
me = AdUser(fbid='me', api=api)
ad_account = me.get_ad_account()
assert ad_account.get_api() == api
```

**Comment by wpromatt** [comment]
@ebzlo Then why does the readme documentation say that using multiple access tokens is supported and the only area where you have to again pass the api instance is with class methods?

**Comment by JDaance** [comment]
I vote that the API should flow to all fetched objects!

How would I set the api on the fetched objects afterwards as it is now? I can't use set_default_api as I have many users at the same time.

**Comment by dylanlingelbach** [comment]
@JDaance: you can use our forked version: https://github.com/Evzdrop/facebook-python-ads-sdk

We try to keep it up to date and have a few other changes there but should get you pointed in the right direction.

Hope this helps!

**Comment by dylanlingelbach** [comment]
@rituparnamukherjee - was this fixed or no longer an issue in later versions of the SDK? Or are you saying you aren't going to fix this?

**Comment by rituparnamukherjee** [comment]
@dylanlingelbach 

Apologies for confusion. We have updated quite a bit on the SDK. Would you mind sending out a PR for this off of the latest SDK version.

**Comment by dylanlingelbach** [comment]
@rituparnamukherjee - ok, our solution is not ready for a PR, it is a pretty quick hack. Can we leave this open until you fix or we open a PR?
