### ISSUE TITLE
Allow CustomAudiences to upload pre-hashed email addresses

### ISSUE THREAD

**Issue by Blackburn29** [facebook/facebook-python-ads-sdk#67]
Currently you are unable to upload pre-hashed SHA-256 hashes since the add_user function does the hashing automatically. There should be an option or logic implemented to upload emails that are already hashed

**Comment by ebzlo** [comment]
That's a good point. Thanks @Blackburn29 I'll work on this next week.

**Comment by Blackburn29** [comment]
@ebzlo any updates on this?

**Comment by rituparnamukherjee** [comment]
This is fixed by last push!
