### ISSUE TITLE
"how different ad objects are used" link in README is broken.

### ISSUE THREAD

**Issue by phuston** [facebook/facebook-python-ads-sdk#70]
This hyperlink in the readme is currently broken, and it would be a great resource to have. 
![screen shot 2015-06-15 at 11 50 11 am](https://cloud.githubusercontent.com/assets/7811805/8167685/c4e94d92-1354-11e5-845a-97e13bada2d4.png)

**Comment by rituparnamukherjee** [comment]
This seems to be working now.
