### ISSUE TITLE
Impressions returned as unicode string, not int

### ISSUE THREAD

**Issue by phuston** [facebook/facebook-python-ads-sdk#71]
In the Insights documentation, the stated return type for the Impressions general field is said to be of type Int: 

![screen shot 2015-06-18 at 2 59 05 pm](https://cloud.githubusercontent.com/assets/7811805/8243287/9ebc9746-15ca-11e5-9eb3-bd962ffdb913.png)

When I am making a get_insight call on an AdAccount object, however, the Impressions field is returned as a unicode string. Here's an example call:

```
account = AdAccount(account_id)

params = {
    'fields': [Insights.Field.impressions,],
    'time_range': {
        'since': '2015-05-15',
        'until': '2015-05-15',
    },
}

stats = account.get_insights(params = params)

print stats
```

What is returned looks like this, and calling type() on the value for "impressions" returns unicode:

```
[<Insights> {
    "date_start": "2015-05-15",
    "date_stop": "2015-05-15",
    "impressions": "27155"
}]
```

Am I missing something here, or are impressions just incorrectly being returned as a unicode string?

**Comment by ebzlo** [comment]
Hey Patrick!

Looks like this is probably just a documentation error. The correct return type should be a numeric string (or just string). I'll update the docs. Thanks for flagging this!

Evan


On Jun 18, 2015, at 6:07 PM, Patrick Huston <notifications@github.com<mailto:notifications@github.com>> wrote:


In the Insights documentation, the stated return type for the Impressions general field is said to be of type Int:

[screen shot 2015-06-18 at 2 59 05 pm]<https://urldefense.proofpoint.com/v1/url?u=https://cloud.githubusercontent.com/assets/7811805/8243287/9ebc9746-15ca-11e5-9eb3-bd962ffdb913.png&k=ZVNjlDMF0FElm4dQtryO4A%3D%3D%0A&r=8RkjuOkfP5iCAEeEXZyC6A%3D%3D%0A&m=ONV3QsQBqR6OGshbsRnF3JVunAksrjqS54fo7NkTSIk%3D%0A&s=152d77bed00595a4e7e360e590d243adaf591bdd5bdedcc05f13ee38a90ae9ae>

When I am making a get_insight call on an AdAccount object, however, the Impressions field is returned as a unicode string. Here's an example call:

account = AdAccount(account_id)

params = {
    'fields': [Insights.Field.impressions,],
    'time_range': {
        'since': '2015-05-15',
        'until': '2015-05-15',
    },
}

stats = account.get_insights(params = params)

print stats


What is returned looks like this, and calling type() on the value for "impressions" returns unicode:

[<Insights> {
    "date_start": "2015-05-15",
    "date_stop": "2015-05-15",
    "impressions": "27155"
}]


Am I missing something here, or are impressions just incorrectly being returned as a unicode string?

**Comment by phuston** [comment]
Thanks for getting back to me so quickly - out of curiosity, why would impressions (a numerical statistic) be returned as a string while every other numerical statistic is returned as an integer or a float?

**Comment by ebzlo** [comment]
We usually return numeric values that can get very large (ids typically) as strings to avoid possible integer overflow issues. It makes it safer to ingest for languages that care about int/bigint. Since this value is typically only used for display (rather than operations), it makes sense to be safe and return a string.

**Comment by phuston** [comment]
That does make sense, thank you for clarifying so quickly. I have one last question for you regarding the SDK - what is the status on making asynchronous calls directly from the SDK? I saw it was in development in January, and I'm wondering if it's available yet. 

Thank you again,
Patrick

**Comment by ebzlo** [comment]
Hey @phuston, it's probably the most requested feature for the SDK and we're working on trying to get it released for 2.4

**Comment by phuston** [comment]
I understand if you can't divulge this information, but do you have
information on the timeline for its release?

Thanks,

Patrick

**Comment by ebzlo** [comment]
I just picked up the task for myself and will try and get it out for you well before then. Feel free to ping me mid next week if you don't see progress. :)

Evan

**Comment by phuston** [comment]
Wow! I really appreciate your help in navigating my way through migrating
to the SDK, and I'm looking forward to seeing asynchronous call being
implemented!

Best,
Patrick

**Comment by phuston** [comment]
@ebzlo, I figured I'd check in again to see how the implementation of the asynchronous calls is coming, and if you have a better feel for an ETA. 

-Patrick
