### ISSUE TITLE
KeyError when trying to read an error

### ISSUE THREAD

**Issue by m-vdb** [facebook/facebook-python-ads-sdk#72]
Backtrace:
```
File ".../facebookads/api.py", line 117, in error
self.body()
File ".../facebookads/exceptions.py", line 99, in __init__
KeyError: 'path'
```

Looks like the error is located [here](https://github.com/facebook/facebook-python-ads-sdk/blob/2.3.3/facebookads/exceptions.py#L92). The `request_context`, i.e. `error._call` has no key "path".

I got this on version `2.3.3` and using a batch query. Looks like this https://github.com/facebook/facebook-python-ads-sdk/blob/2.4.2/facebookads/api.py#L387-L407
is the problem (I don't see a `path` key)

**Comment by rituparnamukherjee** [comment]
Please provide repro steps if you are still seeing this issue.

**Comment by m-vdb** [comment]
@rituparnamukherjee well, the issue is kind of obvious for a code point of view... I can write a unit test that can make it fail

**Comment by aparakian** [comment]
... Yes that sounds kind of obvious @rituparnamukherjee  :/

**Comment by rituparnamukherjee** [comment]
Oh, got it. I guess I misunderstood before. Will fix this soon.

**Comment by rituparnamukherjee** [comment]
This is fixed now!
