### ISSUE TITLE
Checking prefix 'act_' for parent_id.

### ISSUE THREAD

**Issue by hanstzalora** [facebook/facebook-python-ads-sdk#74]
from facebookads import FacebookAdsApi
    from facebookads.objects import CustomAudience

    my_app_id = <APP_ID>
    my_app_secret = '<APP_SECRET>'
    my_access_token = '<ACCESS_TOKEN>'
    FacebookAdsApi.init(my_app_id, my_app_secret, my_access_token)

    AD_ACCOUNT_ID = 1431453467646932

    audience = CustomAudience(parent_id='{}'.format(AD_ACCOUNT_ID))
    audience.update({
        CustomAudience.Field.name: 'someName',
        CustomAudience.Field.subtype: CustomAudience.Subtype.custom,
    })

    audience.remote_create()

When I ran this code it throws an error. But when I change the value of parent_id to `'act_{}'.format(AD_ACCOUNT_ID)'`, the code ran without error. Is this by design or a bug?

I would suggest that there is a check for parent_id whether it has prefix 'act_' or not.

**Comment by ezegolub** [comment]
+1, i'm having the same issue.

**Comment by ebzlo** [comment]
Hey @hanstzalora, this is intended as the root node for an account is `act_[0-9]+`

We unfortunately cannot do a trivial check as `parent_id` can sometimes be `[0-9]+` (in the event of Business Manager, for example).

I will look into possibilities here as we do know which edges depend on an ad account root node.
