### ISSUE TITLE
Question: What is the upgrade plan for the new "Optimization Simplification" in API v2.4?

### ISSUE THREAD

**Issue by cscanlin** [facebook/facebook-python-ads-sdk#76]
Detailed here:
https://developers.facebook.com/docs/marketing-api/optimization_simplification

My question is, when is thew SDK going to begin supporting the new optimization fields, and is there any plan to support both types of optimization during the transition?

Thanks!

**Comment by ebzlo** [comment]
Hey @cscanlin we're working on getting 2.4 in today with all those fields!

**Comment by cscanlin** [comment]
Thanks, you guys are great!
