### ISSUE TITLE
remote_read with batch, response after execute is missing the requested fields.

### ISSUE THREAD

**Issue by parander** [facebook/facebook-python-ads-sdk#8]
Assume s,t are AdGroup objects with valid id's already set and that b is a FacebookAdsApiBatch object.

Without using batch:

s.remote_read(fields=[AdGroup.Field.name, AdGroup.Field.campaign_id])
t.remote_read(fields=[AdGroup.Field.name, AdGroup.Field.campaign_id])

both s,t now contains the fields name and campaign_id, however if the call is made in this way instead:

s.remote_read(fields=[AdGroup.Field.name, AdGroup.Field.campaign_id], batch=b)
t.remote_read(fields=[AdGroup.Field.name, AdGroup.Field.campaign_id], batch=b)
b.execute()

The name and campaign_id fields are not set, the response bodies from the server only has the 'id' value set.

**Comment by facebook-github-bot-9** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by rituparnamukherjee** [comment]
This is similar to issue #152. Will be pushing the update very soon.
