### ISSUE TITLE
The new version should be updated to v2.4 

### ISSUE THREAD

**Issue by fivejjs** [facebook/facebook-python-ads-sdk#80]
I just changed the version in api.py to:
`API_VERSION = 'v2.4'`

**Comment by hugoduar** [comment]
Anyway, it throws an error because of SSL

**Comment by fivejjs** [comment]
@hugoduar  That's can be fixed by: 
```requests.packages.urllib3.disable_warnings()```

**Comment by fivejjs** [comment]
Lastest code in api.py fix this issue.
