### ISSUE TITLE
Custom Audiences --list request does not work

### ISSUE THREAD

**Issue by thenaturalist** [facebook/facebook-python-ads-sdk#83]
The URL displayed in the executing command shell is 
"https://grap.facebook.com/v2.4/ [id of adaccount]/customaudiences"
while in the actual Graph Explorer on the FB website it is
"https://grap.facebook.com/v2.4/ **act_** [id of adaccount]/customaudiences"

I get a "Call was not successful"/ "Unsupported get request" message, Status 400.

**Comment by paulbain** [comment]
did you prefix the account id with 'act_' ?

**Comment by thenaturalist** [comment]
I'm a noob. My bad... 
I took 'act_id' as a literal, complete placeholder. Of course adding 'act_' in the config solves the issue...
Hidden in plain sight.

Thanks for the quick response.
