### ISSUE TITLE
bid_type not available in AdSet object

### ISSUE THREAD

**Issue by sibiyes** [facebook/facebook-python-ads-sdk#85]
Hello,

I am currently using version 2.4

I found that I am not able to set bid_type for the ad set that I create. There is no bid_type member available in the AdSet object. I would like to set the bid_type to CPC. The ad set that I create defaults to CPA.

How to work this issue ? Any idea how to set bid_type of the ad set to CPC

Thanks

Sibi

**Comment by ebzlo** [comment]
Hey @sibiyes, `bid_type` was removed in version 2.4 of the SDK. For more information, check this document: https://developers.facebook.com/docs/marketing-api/optimization_simplification
