### ISSUE TITLE
Update Docsmith link

### ISSUE THREAD

**Issue by thomascirca** [facebook/facebook-python-ads-sdk#86]
According to this https://github.com/facebook/facebook-python-ads-sdk/tree/master/examples/docs , it's possible to generate documentation through a tool called "DocSmith". Unfortunately, the link (https://our.intern.facebook.com/intern/wiki/Solutions_Engineering/Devsite_Dynamic_Doc_Code_Blocks) doesn't seem to point at anything anymore. Would love to see what DocSmith does since googling "Facebook DocSmith" gives me a list of people named "Doc Smith".

**Comment by rituparnamukherjee** [comment]
Actually this feature is not available. We have updated the repo to reflect the latest state.
