### ISSUE TITLE
Insights: "roas is not valid for fields param"

### ISSUE THREAD

**Issue by cscanlin** [facebook/facebook-python-ads-sdk#88]
This bug was validated in the Ads API v2.4 Q&A:
https://www.facebook.com/events/873155332753388/878318465570408/

Reposting this here for better issue tracking

**Comment by rituparnamukherjee** [comment]
This is fixed in the latest version.

**Comment by cscanlin** [comment]
Just to clarify, "fixed" really means "removed" in this case, correct?

**Comment by rituparnamukherjee** [comment]
Yes, that is correct.

**Comment by cscanlin** [comment]
Is there any chance this will be added back in a future update? This functionality would save a few dozen lines of code from by program, especially if it could be used in the filter parameter.

**Comment by rituparnamukherjee** [comment]
It is hard to say at this point if the field will be made available again in later versions.
