### ISSUE TITLE
AdAccount.get_report_stats(params, async=True)

### ISSUE THREAD

**Issue by jpercent** [facebook/facebook-python-ads-sdk#89]
It doesn't look like this was implemented until v2.4, but it is deprecated in v2.4 on the server-side. It exists in the documentation for v2.3, but it's not in any of the code as far as I can tell (please let me know if it is). It is in the docs for v2.4 too, but the calls are deprecated on the server side and fail! FML.

It looks like a backport would need at least AdAccount.iterage_edge_async and objects.AsyncJob. 
Is there a chance we can get this backported to v2.3? I can help. Are there any huge gotchas that make such a backport difficult? 

Sucks that it's in the docs, but doesn't work anywhere. Seems like v2.3 is the best shot at providing a workaround. Any guidance is greatly appreciated.

**Comment by rituparnamukherjee** [comment]
The report_stats endpoint was deprecated with the advert of /insights endpoint. You can use this endpoint for getting similar stats. More details can be found at https://developers.facebook.com/docs/marketing-api/insights/v2.4
