### ISSUE TITLE
get_reach_estimate

### ISSUE THREAD

**Issue by pandamako** [facebook/facebook-python-ads-sdk#90]
Hello.
I try to get estiamation by this documentation https://www.facebookmarketingdevelopers.com/docs/python but i don't receive `cpa_curve_data` field.
What do I wrong?

**Comment by rituparnamukherjee** [comment]
Hello,

This field is not available in the API anymore. We are updating the SDK docs to reflect the same.

**Comment by pandamako** [comment]
@rituparnamukherjee but this value still use in facebook's UI. How I can calculate percentage of reach of the auditory?
