### ISSUE TITLE
Cannot create AdLabel on AdCreative

### ISSUE THREAD

**Issue by m-vdb** [facebook/facebook-python-ads-sdk#96]
Nowhere in the API documentation is mentioned the fact that it is possible to add labels on creatives. So I think you code should be updated and remove the `HasAdLabel` mixin inheritance from the `AdCreative` class [here](https://github.com/facebook/facebook-python-ads-sdk/blob/master/facebookads/objects.py#L1579). If I'm mistaken, your API doc should be updated...

Got the following error:
```
in call raise fb_response.error() FacebookRequestError: Message: Call was not successful Method: GET Path: https://graph.facebook.com/v2.4/6034071669641/adlabels Params: {'summary': 'true'} Status: 400 Response: { "error": { "message": "(#100) Invalid edge (adlabels) on node type (AdCreative)", "code": 100, "type": "OAuthException", "fbtrace_id": "DElUVn10w2E" } }
```

**Comment by aparakian** [comment]
Actually the problem is that the Edge is not present between AdCreative and AdLabel so we cannot iterateEdge to code the (also missing) get_ad_labels() function from AdCreative and have to find a workaround...

**Comment by rituparnamukherjee** [comment]
The section under https://developers.facebook.com/docs/marketing-api/reference/ad-label#Updating talks about how to add labels to existing ad objects. AdGroup is used as example, this applies to all ad objects including creatives.

You can get adlabels associated with an adcreative using field=adlabels.
adcreative.remote_read(fields=['adlabels'])

 It is not an edge, therefore there was no get_ad_labels method created for ad objects other than ad account.

**Comment by m-vdb** [comment]
ok, don't like it, but ok

**Comment by aparakian** [comment]
yes but it does not return an AdLabel to remote_read the field, it returns a dictionary with id and name key... So have to wrap it into the AdLabel class... Kind of a bummer but ok

**Comment by m-vdb** [comment]
I'll second @aparakian on that. There clearly is a wrapper missing
