### ISSUE TITLE
redownload not working for AdGroup update

### ISSUE THREAD

**Issue by fzheng** [facebook/facebook-python-ads-sdk#99]
for example, when trying to update AdGroup status from active to paused
AdGroup: <AdGroup> {
    "adgroup_status": "PAUSED",
    "id": 6033822058035,
    "redownload": true
}
the response of remote_update only contains adgroup_status, id and redownload fields, it doesn't have complete fields as curl request does

**Comment by rituparnamukherjee** [comment]
Hi fzheng,

This will be fixed soon.

**Comment by vaishnav-piyush** [comment]
Is this issue fixed now ? 

I am trying to use redownload to download all fields of an AdSet but it doesn't seem to be working. 
Here is my code: 

ad_set = AdSet('6049562095738')
response=ad_set.api_get(params={AdSet.Field.redownload:True})
print(response)

and I get
<AdSet> {
    "id": "6049562095738"
}
